app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/home.css.scss
app/assets/stylesheets/peoplefinder/people.css.scss
app/views/peoplefinder/people/show.html.haml

Mobile phones love the peoplefinder now

Responsive fixes

---

app/controllers/peoplefinder/application_controller.rb
app/controllers/peoplefinder/people_controller.rb
config/locales/en.yml
spec/controllers/peoplefinder/people_controller_spec.rb
spec/features/person_maintenance_spec.rb

"As a user that has updated someone else's profile, I need to know that that person has been notified"

Notify about notification

---

app/assets/stylesheets/peoplefinder/groups.css.scss
app/views/peoplefinder/groups/_detail.html.haml

Brought the team leader photo in team leadership page in line with the text.
Trello card: https://trello.com/c/8F2Vbck8/194-s-position-headline-on-team-pages-in-line-with-main-image

Headline position

---

app/models/peoplefinder/concerns/sanitisable.rb
app/models/peoplefinder/person.rb
spec/models/peoplefinder/concerns/sanitisable_spec.rb

I've decided to create a concern for this as we'll include it in the Group model as well. 
The spec is written for a generic ActiveModel object, not tight to Person as the other concerns. 
@Najaf @cfq

Strip whitespaces from name and email

---

app/assets/stylesheets/peoplefinder/application.scss

Increased the size of breadcrumbs

---

app/services/peoplefinder/csv_people_importer.rb
lib/tasks/peoplefinder/import.rake
spec/services/peoplefinder/csv_people_importer_spec.rb

REBASED - I had to rebase on master to pick up latest I18N changes.
This is the first part of the import script which validates each row and returns list of errors based on the Peoplefinder::Person validation rules.
I haven't put anything in the README, because I think it's better to do it when the import is completed.
Also this is better to run from the wrapper application, because the current validation rules also take into account the list of valid e-mail domainsl

Verify csv for import - rebased

---

app/assets/stylesheets/peoplefinder/groups.css.scss
app/views/peoplefinder/groups/_subgroup.html.haml

https://trello.com/c/am1tyJ4y/191-m-make-the-whole-target-area-of-the-team-title-plus-the-limited-character-count-for-team-description-used-on-team-index-pages-cl

Subgroup target links massive

---

app/assets/stylesheets/peoplefinder/application.scss
app/helpers/peoplefinder/application_helper.rb
app/views/layouts/peoplefinder/application.html.haml
peoplefinder.gemspec

@novotnyjakub @cfq @threedaymonk 
Makes the app title a clickable link, required changes to moj internal template.
https://trello.com/c/qe7OxYhM

App title as link

---

app/views/peoplefinder/people/_form.html.haml
config/locales/en.yml

@threedaymonk do you have an opinion on testing this?
@cfq as discussed it would be good if you could eyeball this too. Do you think using the `.form-hint` class is appropriate here?
https://trello.com/c/SZyZCNTF

Adds explanation text to email field in people form

---

app/views/peoplefinder/sessions/_login_page.html.haml
config/locales/en.yml
spec/features/omni_auth_authentication_spec.rb
spec/features/token_authentication_spec.rb
spec/support/login.rb

After merging this into peoplefinder, the similarly-named branch in moj_peoplefinder should also be merged.

Explain auth procedure on login page

---

app/assets/stylesheets/peoplefinder/home.css.scss
app/views/peoplefinder/home/show.html.haml
app/views/peoplefinder/shared/_search.html.haml
config/locales/en.yml
spec/features/home_spec.rb

Update copy and fix markup problems identified in accessibility audit (header hierarchy and text not in `<p>`).

Update home page copy

---

app/assets/javascripts/peoplefinder/wordlimit.js
app/assets/stylesheets/peoplefinder/application.scss
app/models/peoplefinder/group.rb
app/views/peoplefinder/groups/_form.html.haml
spec/models/peoplefinder/group_spec.rb

It's now limited to 1000 characters with a live counter in the front end.

Limit "about team" length

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/people.css.scss
app/views/peoplefinder/people/show.html.haml

Trello card: https://trello.com/c/vqxDOJXG/79-s-as-someone-looking-at-a-profile-i-need-context-so-that-i-can-understand-what-the-information-is-on-someone-s-profile

Info labels

---

app/models/peoplefinder/concerns/concatenated_fields.rb
app/models/peoplefinder/concerns/searchable.rb
app/models/peoplefinder/group.rb
app/models/peoplefinder/membership.rb
app/models/peoplefinder/person.rb
spec/models/peoplefinder/concerns/concatenated_fields_spec.rb
spec/models/peoplefinder/person_search_spec.rb

Remove dead code, simplify, and make the `Searchable` concern actually reusable.

Tidy models

---

app/controllers/peoplefinder/api/application_controller.rb
app/controllers/peoplefinder/api/people_controller.rb
config/routes.rb
spec/controllers/peoplefinder/api/people_controller_spec.rb

API endpoint /api/people/<SLUG>

API endpoint for people#show and API controller

---

app/assets/stylesheets/peoplefinder/application.scss

Put back the list styles that GDS took away

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie7.scss
app/assets/stylesheets/peoplefinder/peoplefinder-lt-ie9.scss
app/assets/stylesheets/peoplefinder/peoplefinder_colours.scss
app/assets/stylesheets/peoplefinder/peoplefinder_ie_colours.scss
app/views/layouts/_shared.html.haml
app/views/sessions/_login_page.html.haml
config/initializers/assets.rb

This is all the fixes from PR 102 except for the changes to labels that resulted in label text being erroneous.

Fix IE issues that don't cause regressions

---

.travis.yml

Travis is watching our PRs again, but he needs an updated database configuration now that there is no engine.

Fix Travis CI integration

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie7.scss

IE7 background colour missing from edit links 
Safari (+) Icon trimmed at the bottom

Browser specific bugs

---

app/assets/stylesheets/peoplefinder/application.scss
app/controllers/admin/person_uploads_controller.rb
app/controllers/application_controller.rb
app/models/person_upload.rb
app/services/csv_people_importer.rb
app/views/admin/person_uploads/_errors.html.haml
app/views/admin/person_uploads/_form.html.haml
app/views/admin/person_uploads/create.html.haml
app/views/admin/person_uploads/new.html.haml
config/locales/en.yml
config/routes.rb
spec/features/csv_upload_spec.rb
spec/fixtures/invalid.csv
spec/fixtures/valid.csv
spec/models/person_upload_spec.rb
spec/services/csv_people_importer_spec.rb

Don't merge this yet: we're waiting for final copy.

CSV upload interface

---

smoke_test

[Story 328](https://trello.com/c/T4E207TH/328-m-smoke-tests)
Set the following environment variables:
* HOST - the root of the server to be tested, e.g. http://example.com/
* EMAIL_ADDRESS - the email address to sign in with
* EMAIL_PASSWORD - the IMAP password
Google Apps IMAP is assumed, and the account must have IMAP access configured. For the password, generate an app-specific password (this is necessary if two-factor authentication is enabled).
Run the test:
$ bundle exec ./smoke_test
Successful output will look like this:
Request token ... OK
Fetch token email ... wait 2s ... OK
Sign in ... OK
Edit profile ... OK
Search for profile ... wait 2s ... OK
On success, the return code is zero. Failure will result in a non-zero return code.

Smoke test for staging and production servers

---

app/assets/javascripts/peoplefinder/help-area.js
app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/help-area.scss
app/assets/stylesheets/peoplefinder/home.css.scss
app/assets/stylesheets/peoplefinder/search_box.css.scss
app/views/groups/_form.html.haml
app/views/home/show.html.haml
app/views/people/_form.html.haml
app/views/sessions/_login_page.html.haml
app/views/shared/_search.html.haml
app/views/token_mailer/new_token_email.html.erb
app/views/user_update_mailer/deleted_profile_email.html.erb
app/views/user_update_mailer/new_profile_email.html.erb
app/views/user_update_mailer/updated_profile_email.html.erb
config/locales/en.yml
spec/features/omni_auth_authentication_spec.rb
spec/features/token_authentication_spec.rb
spec/support/login.rb
spec/support/profile.rb

Copy changes as requested in 
https://trello.com/c/BA7BZRTP
and
https://trello.com/c/7JLXIOn4
Emails will need testing. I think I've got all the ones that currently exist, but I'm not 100% sure. Copy for emails is here: https://docs.google.com/a/digital.justice.gov.uk/document/d/1uHdXLCHdZYKAUNJQvDKg_nAPDq_kN-GWuUmW5i3KAXM/edit

Copy changes

---

app/controllers/application_controller.rb
app/controllers/people_controller.rb
app/controllers/search_controller.rb
app/models/person.rb
app/services/person_search.rb
app/views/people/_breadcrumbs.html.haml
spec/models/person_spec.rb
spec/services/person_search_spec.rb

Make Person a bit less of a god object by extracting and deleting.

Clean up Person

---

docker/rails/Dockerfile

@kyriakosoikonomakos can you review this.

Install PhantomJS from the DSD repo

---

app/views/people/_profile.html.haml

Even if it's complete, it can still be wrong.

Allow reporting/improvement of complete profiles

---

app/models/suggestion.rb
app/views/suggestions/new.html.haml

Add phone number and profile image to the list of things that can be reported as potentially incorrect.

Report more incorrect fields

---

config/database.yml

which is parsed on the rails side automagically.

Removed production database settings as we provide postgresql url

---

config/application.rb

This reverts commit e231c481f3e58ee2cc3e26e882d970eb58c9d233.

Revert "Change comment to test a release for IR"

---

README.md

Self-evident, really.  We really should be adding this to every repo we
possibly can.

Add codeclimate and coverage badges

---

Gemfile
Gemfile.lock
README.md

A new starter to the team has highlighted gaps in our readme install steps.

Update readme with homebrew, java, postgresql install steps

---

app/views/people/_membership_fields.html.haml
config/locales/en.yml
spec/features/person_membership_spec.rb

Add yes/no radio buttons for team leader and subscribe questions on profile edit view.

WIP: Add yes/no radio buttons for team leader and subscribe

---

app/controllers/metrics/team_descriptions_controller.rb
app/models/group.rb
config/routes.rb
spec/controllers/metrics/team_descriptions_controller_spec.rb
spec/controllers/people_controller_spec.rb
spec/models/group_spec.rb

Add controller action to return geckoboard JSON to show this metric on geckoboard dashboard.

Add metric for percentage of teams with a description

---

app/assets/javascripts/peoplefinder/photo_upload.js

Apply photo upload save button javascript to new person form.

Fix issue with failing save button on new person page

---

Gemfile
Gemfile.lock
Guardfile
bin/rails
bin/rspec
bin/spring

Configure guard to run: bundle exec spring rspec

Add spring-commands-rspec and rb-fsevent to improve rspec speed

---

app/assets/stylesheets/application.scss
app/controllers/people_controller.rb
app/models/person.rb
app/services/person_search.rb
app/views/people/_form.html.haml
app/views/people/_profile.html.haml
app/views/people/confirm.html.haml
app/views/search/_person.html.haml
config/locales/en.yml
db/migrate/20160308105233_add_current_project_to_person.rb
db/structure.sql
spec/features/search_spec.rb
spec/services/person_search_spec.rb
spec/support/profile.rb

* Add current project(s) input field to person edit form
* Display current project(s) in search results
* Ability to search on current project text

Add current project(s) field to person's profile

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/groups.css.scss
app/assets/stylesheets/peoplefinder/maginot.scss
app/assets/stylesheets/peoplefinder/people.css.scss
app/views/groups/_detail.html.haml
app/views/groups/_leaderships.html.haml
app/views/groups/show.html.haml
app/views/layouts/application.html.haml
app/views/layouts/home.html.haml
app/views/people/_profile.html.haml
app/views/shared/_loginout.html.haml
app/views/shared/_search.html.haml
spec/features/group_browsing_spec.rb
spec/features/home_spec.rb
spec/features/person_maintenance_spec.rb
spec/features/person_membership_spec.rb
spec/features/suggestion_spec.rb

- Redesign of page header to get more content above the fold.
- Redesign of team view to distinguish it from person view.

Design changes to page header and team view

---

app/controllers/problem_reports_controller.rb
config/locales/en.yml

Use flash notice to set confirmation message.

Show confirmation when problem report is submitted

---

.env
Gemfile
spec/features/group_maintenance_spec.rb

A test is intermittently failing probably
due to javascript.

use wait time to improve flicker

---

spec/features/report_a_problem_spec.rb

being causing bye an around hook with timecop

fix flickering spec

---

app/assets/javascripts/peoplefinder/photo_upload.js.erb
app/controllers/profile_photos_controller.rb
spec/controllers/profile_photos_controller_spec.rb

prevent selection of files that are over
10M as only files over 3M will be validated
and the caching of large files is slow.

add javascript limit for file upload

---

app/models/token.rb
spec/models/token_spec.rb

email sent to GSI email accounts from dev and
staging are being `spent` prematurely. This is
likely being caused by an email scanner following
links in the email and thereby prematurely triggering
login.
Findings: in the <server>.access.json logs
on the server you can see that, following an
email login request being sent, a request from
an http_user_agent identified as
```
"http_user_agent": "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)"
```
is hitting the token login endpoint, and thereby
spending the token.
It is possible that because prod is hosted within
gov.uk it does not trigger the same scanning.

add token login exception for dev and staging

---

app/services/person_csv_importer.rb
app/services/person_csv_parser.rb
spec/factories.rb
spec/fixtures/valid_with_optionals.csv
spec/helpers/upload_helper_spec.rb
spec/services/person_csv_importer_spec.rb
spec/services/person_csv_parser_spec.rb

for mass person creation of users requiring
pager numbers.

add pager number as optional field to csv uploader

---

app/controllers/admin/person_uploads_controller.rb
app/controllers/application_controller.rb
app/models/readonly_user.rb

deployment environments are not enforcing
login. local development is?!

debug csv uploader access

---

app/controllers/search_controller.rb
app/services/group_search.rb
app/services/person_search.rb
app/views/search/index.html.haml
spec/features/search_spec.rb
spec/services/group_search_spec.rb

search result summary was not reflecting teams in its count nor conditional display logic

Fix search result summary

---

README.md
app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie7.css.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie9.css.scss
app/assets/stylesheets/peoplefinder/peoplefinder-lt-ie9.css.scss
app/models/readonly_user.rb
app/views/layouts/_footer.html.haml
app/views/layouts/_shared.html.haml
app/views/layouts/application.html.haml
app/views/shared/_loginout.html.haml
config/initializers/assets.rb
spec/features/report_a_problem_spec.rb

various IE7, 8 and 9 styling problems have existed for quite a while. This is the first of several 
PRs to fix them. including:

More ie styling fixes

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-gt-ie9.css.scss
config/initializers/assets.rb

moj internal template settings were not
being respected.

fix main content width in IE10+

---

spec/mailers/group_update_mailer_spec.rb
spec/mailers/previews/user_update_mailer_preview.rb
spec/mailers/reminder_mailer_spec.rb
spec/mailers/suggestion_mailer_spec.rb
spec/mailers/user_update_mailer_spec.rb
spec/support/shared_examples_for_mailers.rb

New email layout includes a banner with image

add shared mailer template example spec

---

app/views/groups/organogram.html.haml

design and UR identified this as an issue.

switch dsiaply order of people and teams in organogram

---

app/assets/javascripts/analytics/virtual_pageview.coffee
app/assets/javascripts/peoplefinder/analytics.coffee
app/helpers/analytics_helper.rb
app/helpers/application_helper.rb
app/helpers/people_helper.rb
app/views/people/_completeness.html.haml
app/views/people/_profile.html.haml
app/views/sessions/_login_page.html.haml
app/views/shared/_edit_links_NOT_USED.html.haml
spec/helpers/analytics_helper_spec.rb
spec/helpers/people_helper_spec.rb
spec/javascripts/analytics/analytics_event_spec.coffee

To assist with tracking of login and profile editing issues some virtual page views have been created for Google Analytics to make use of.

Add virtual page view and event tracking for signin in request

---

app/helpers/analytics_helper.rb
app/views/groups/_detail.html.haml
app/views/groups/_heading_links.html.haml
app/views/groups/show.html.haml
spec/helpers/analytics_helper_spec.rb

additional GA virtual page view to assist in tracking of team editing

Team edit google analytics virtual pageview

---

app/models/concerns/geckoboard_datasets.rb
lib/geckoboard_publisher/profiles_percentage_report.rb
spec/factories.rb
spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb

Many people are either in no team at all or just
under MoJ.

add geckoboard dataset for idenitifying unassigned people

---

.rubocop.yml
.rubocop_todo.yml
Gemfile
Gemfile.lock
config/schedule.rb
spec/config/schedule_spec.rb
spec/support/matchers/whenever_matchers.rb

nightly scheduling of geckoboard dataset (re)creation for KPI metrics

Geckoboard dataset scheduling

---

config/locales/en.yml
spec/javascripts/peoplefinder/team_selector_spec.js

suggestion by designer attempting to reduce misuse
of the leadership of a team issue.

change leadership question content

---

app/models/concerns/geckoboard_datasets.rb
config/schedule.rb
lib/geckoboard_publisher/profile_completions_report.rb
lib/geckoboard_publisher/report.rb
spec/config/schedule_spec.rb
spec/factories.rb
spec/lib/geckoboard_publisher/profile_completions_report_spec.rb
spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb
spec/support/matchers/general_matchers.rb
spec/support/shared_examples_for_geckoboard_reports.rb

To further assist in determining which teams are
less likely to be completing partcular profile elements.

add profile completion by team geckoboard dataset report

---

app/presenters/membership_changes_presenter.rb
spec/mailers/user_update_mailer_spec.rb

change wording for membership changes

---

app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie7.css.scss
app/controllers/application_controller.rb
app/helpers/application_helper.rb

awaiting approval from designer

Change error flash styling

---

app/assets/stylesheets/peoplefinder/email.css.scss
app/views/token_mailer/new_token_email.html.haml

User testing with CRC/Probation/IE6 users. To encourage
users of IE6 to use Firefox instead.

modify content of new token email

---

app/views/token_mailer/new_token_email.html.haml

fix typo in new token email wording

---

app/models/person.rb
app/queries/namesakes_query.rb
spec/queries/namesakes_query_spec.rb

replace inline query with query object

NamesakeQuery

---

app/assets/stylesheets/peoplefinder/people.css.scss
app/views/search/index.html.haml
app/views/sessions/person_confirm.html.haml

JIRA:
https://dsdmoj.atlassian.net/browse/PFT-159
A larger callout to limit the amount of duplicate profiles

Duplicate profile found

---

app/assets/stylesheets/peoplefinder/application.scss
app/views/people/_profile.html.haml
app/views/people/edit.html.haml
spec/features/audit_trail_spec.rb
spec/features/flash_spec.rb
spec/features/person_edit_notifications_spec.rb
spec/features/person_maintenance_spec.rb
spec/features/regression_spec.rb

JIRA:
https://dsdmoj.atlassian.net/browse/PFT-168
Implemented the new design for the delete link

Delete profile link

---

app/views/layouts/_shared.html.haml

Applies IE7 stylesheets to IE6. This will handle most stylig issues

modify shim to use IE 7 styles sheets for IE6

---

README.md
app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/search.css.scss
app/models/concerns/searchable.rb
app/models/person.rb
app/services/person_search.rb
app/services/search_results.rb
app/views/people/confirm.html.haml
app/views/search/_person.html.haml
app/views/search/_person_confirmation.html.haml
app/views/search/index.html.haml
app/views/sessions/person_confirm.html.haml
lib/tasks/peoplefinder/data.rake
lib/tasks/peoplefinder/es.rake
spec/controllers/search_controller_spec.rb
spec/features/search_spec.rb
spec/models/person_spec.rb
spec/queries/distinct_membership_query_spec.rb
spec/services/person_search_spec.rb
spec/support/elastic_search_helper.rb
spec/views/search/_person.html.haml_spec.rb

Search highlighting

---

app/assets/stylesheets/peoplefinder/admin.scss
app/assets/stylesheets/peoplefinder/application.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie7.css.scss
app/assets/stylesheets/peoplefinder/peoplefinder-ie9.css.scss
app/assets/stylesheets/peoplefinder/peoplefinder-lt-ie9.css.scss
app/controllers/admin/management_controller.rb
app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/policies/admin/management_policy.rb
app/policies/admin/person_upload_policy.rb
app/policies/application_policy.rb
app/queries/all_user_roles_query.rb
app/queries/user_behavior_query.rb
app/views/admin/management/show.html.haml
app/views/shared/_loginout.html.haml
config/locales/en.yml
config/routes.rb
lib/csv_publisher/user_behavior_report.rb
spec/features/csv_upload_spec.rb
spec/features/login_flow_spec.rb
spec/lib/csv_publisher/user_behavior_report_spec.rb
spec/policies/admin/management_policy_spec.rb
spec/policies/admin/person_upload_policy_spec.rb
spec/queries/all_user_roles_query_spec.rb
spec/queries/user_behavior_query_spec.rb
spec/support/matchers/sql_matchers.rb
spec/support/pages/base.rb

Add a CSV report that extracts data to identify user behaviour for user research. Includes creation and authorisation of a general admin interface for accessing/downloading the report.
see [JIRA Ticket](https://dsdmoj.atlassian.net/browse/PFT-243)

Role and login reporting

---

app/jobs/generate_report_job.rb
app/queries/user_behavior_query.rb
app/views/admin/management/show.html.haml
spec/features/management_spec.rb
spec/jobs/generate_report_job_spec.rb
spec/queries/user_behavior_query_spec.rb
spec/support/pages/management.rb

remove a subquery that was very slow on prod data.

Remove slow subquery

---

app/controllers/admin/management_controller.rb
app/models/report.rb
db/migrate/20170228181641_create_reports.rb
db/schema.rb
lib/csv_publisher/user_behavior_report.rb
spec/factories.rb
spec/lib/csv_publisher/user_behavior_report_spec.rb
spec/models/report_spec.rb
spec/services/person_search_spec.rb
spec/spec_helper.rb
spec/support/matchers/file_matchers.rb

reports are generated by the worker container and must
therefore be made available to the app container
via the db.

add central report storage in database

---

app/assets/javascripts/peoplefinder/photo_upload.js.erb
app/models/profile_photo.rb
spec/models/profile_photo_spec.rb

increase max size of images inline with expected limits for office 365 account profile images

change image max upload byte size to 6

---

app/assets/stylesheets/modules/_module-complete-indecator.scss
app/assets/stylesheets/modules/_module-flash-messages.scss
app/assets/stylesheets/modules/_module-media.scss
app/views/people/_day.html.haml
app/views/people/_profile.html.haml
app/views/people/_request_information.html.haml

MERGE TO FE-Update branch
https://dsdmoj.atlassian.net/browse/PFT-279

Profile page: as is rebuild plus

---

app/assets/stylesheets/modules/_module-search-box.scss
app/views/groups/people_outside_subteams.html.haml
app/views/groups/show.html.haml

https://dsdmoj.atlassian.net/browse/PFT-289
What the PR does:
Main search module placement and styling

Search: main search input placement

---

spec/validators/email_validator_spec.rb
spec/validators/file_size_validator_spec.rb
spec/validators/image_dimensions_validator_spec.rb

add missing spec for file size validator

---

app/controllers/people_controller.rb
app/uploaders/image_uploader.rb
app/views/people/_completeness.html.haml
app/views/people/_profile.html.haml
app/views/people/edit.html.haml
app/views/people/new.html.haml
spec/controllers/people_controller_spec.rb
spec/helpers/people_helper_spec.rb
spec/models/profile_photo_spec.rb
spec/support/pages/sections/profile_form.rb
spec/uploaders/image_uploader_spec.rb

Tidy up all code related to removed preview functionality

remove preview functionality

---

app/assets/javascripts/modules/moj.wordcount.js
app/assets/stylesheets/modules/_module-team-selector.scss
app/assets/stylesheets/modules/_module-textarea-help.scss
app/views/groups/_form.html.haml

https://dsdmoj.atlassian.net/browse/PFT-282

Edit Team: group selector implementation

---

app/assets/stylesheets/elements-local/_textarea.scss
app/assets/stylesheets/modules/_module-feedback-form.scss
app/views/groups/new.html.haml
config/locales/en.yml

https://dsdmoj.atlassian.net/browse/PFT-309

New Team: as-is rebuild

---

app/assets/stylesheets/modules/_module-subgroups.scss
app/assets/stylesheets/modules/_module-team-subgroup.scss
app/views/groups/_subgroup.html.haml
app/views/groups/_teams_in_team.html.haml
app/views/home/show.html.haml

https://dsdmoj.atlassian.net/browse/PFT-310

View Module: Sub group layout

---

app/assets/stylesheets/modules/_module-media.scss
app/views/groups/people_outside_subteams.html.haml
app/views/people/_summary.html.haml

https://dsdmoj.atlassian.net/browse/PFT-300

Teams: Not assigned people page

---

app/assets/stylesheets/modules/_module-pagination.scss
app/views/groups/_all_people_pagination.html.haml
app/views/groups/all_people.html.haml

https://dsdmoj.atlassian.net/browse/PFT-315

Teams: All people in a team as-is rebuild

---

app/assets/javascripts/application.js
app/assets/javascripts/peoplefinder/photo_upload.js.erb
app/assets/stylesheets/application.scss
app/assets/stylesheets/elements-local/_typography.scss
app/assets/stylesheets/modules/_module-media.scss
app/assets/stylesheets/modules/_xmodule_person_photos.scss
app/views/person_image/_breadcrumbs.html.haml
app/views/person_image/edit.html.haml

https://dsdmoj.atlassian.net/browse/PFT-317

Profile: create/update profile picture

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/team_selector.js
app/views/people/_form.html.haml
app/views/people/_membership_fields.html.haml
app/views/search/_person_confirmation.html.haml
app/views/sessions/person_confirm.html.haml
config/locales/en.yml

https://dsdmoj.atlassian.net/browse/PFT-268

Edit profile: Main layout + GDS form

---

app/assets/stylesheets/modules/_module-feedback-form.scss
app/views/shared/_feedback_form.html.haml
app/views/tokens/create.html.haml
config/locales/en.yml

https://dsdmoj.atlassian.net/browse/PFT-314

Token sent: confirmation page as-is rebuild

---

app/assets/stylesheets/modules/_xmodule_organogram.scss
app/views/groups/organogram.html.haml

https://dsdmoj.atlassian.net/browse/PFT-281

Team: Organograms rebuild

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/moj.sample.js
app/assets/javascripts/modules/team_selector.js
app/assets/stylesheets/application-ie6.scss
app/assets/stylesheets/application-ie7.scss
app/assets/stylesheets/application-ie8.scss
app/assets/stylesheets/application.scss
app/views/layouts/application.html.haml
config/initializers/assets.rb

https://dsdmoj.atlassian.net/browse/PFT-360

IE Support: missing GDS stylesheets

---

app/assets/stylesheets/elements-local/_anchors.scss
app/assets/stylesheets/elements-local/_footer.scss
app/views/groups/people_outside_subteams.html.haml
app/views/groups/show.html.haml
app/views/home/show.html.haml
app/views/people/_form.html.haml

- All links no text decoration. Hover with underline
- Hide generic Gov licence in footer
- Edit profile section headers
- Back button styling
- removed debug code

Homepage: general cascading amends

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/team_selector.js

https://dsdmoj.atlassian.net/browse/PFT-368

GDS Checkboxes: re-init after error state

---

app/assets/stylesheets/elements-local/_anchors.scss
app/views/shared/_search.html.haml

https://dsdmoj.atlassian.net/browse/PFT-371

Create Profile: Link missing icon

---

app/assets/stylesheets/modules/_module-media.scss

https://dsdmoj.atlassian.net/browse/PFT-369

Edit profile: picture size is too big

---

app/views/groups/people_outside_subteams.html.haml
app/views/layouts/application.html.haml
app/views/people/_profile.html.haml
app/views/search/_person.html.haml
app/views/search/_person_confirmation.html.haml
app/views/search/_team.html.haml
app/views/search/index.html.haml
app/views/shared/_loginout.html.haml
app/views/tokens/create.html.haml
spec/features/audit_trail_spec.rb
spec/features/cookie_message_spec.rb
spec/features/flash_spec.rb
spec/features/group_browsing_spec.rb
spec/features/group_maintenance_spec.rb
spec/features/person_browsing_spec.rb
spec/features/person_edit_notifications_spec.rb
spec/features/person_maintenance_spec.rb
spec/features/person_membership_spec.rb
spec/features/search_spec.rb
spec/support/pages/base.rb
spec/support/pages/login.rb
spec/support/pages/token_created.rb
spec/support/profile.rb
spec/views/search/_person.html.haml_spec.rb

https://dsdmoj.atlassian.net/browse/PFT-301
TO DO:
rspec ./spec/features/cookie_message_spec.rb
rspec ./spec/features/group_browsing_spec.rb
rspec ./spec/features/group_maintenance_spec.rb
rspec ./spec/features/login_flow_spec.rb
rspec ./spec/features/login_page_spec.rb
rspec ./spec/features/management_spec.rb
rspec ./spec/features/person_browsing_spec.rb
rspec ./spec/features/person_membership_spec.rb
rspec ./spec/features/search_spec.rb
rspec ./spec/features/suggestion_spec.rb
rspec ./spec/features/token_authentication_spec.rb
rspec ./spec/views/search/_person.html.haml_spec.rb

Fix feature specs

---

app/assets/stylesheets/elements-local/_typography.scss
app/assets/stylesheets/modules/_xmodule_person_photos.scss
app/views/person_image/edit.html.haml

https://dsdmoj.atlassian.net/browse/PFT-374

Edit picture: drag / drop container

---

app/controllers/groups_controller.rb
app/controllers/people_controller.rb
app/views/groups/_form.html.haml
app/views/groups/edit.html.haml
app/views/groups/new.html.haml
app/views/people/_form.html.haml
app/views/people/edit.html.haml
app/views/people/new.html.haml
app/views/sessions/_login_page.html.haml

https://dsdmoj.atlassian.net/browse/PFT-367

Error messages: General review

---

app/views/group_update_mailer/inform_subscriber.html.haml
app/views/user_update_mailer/updated_profile_email.html.haml

https://dsdmoj.atlassian.net/browse/PFT-379

Email: remove full stops from links

---

app/views/people/_form.html.haml

https://dsdmoj.atlassian.net/browse/PFT-385

Edit profile: Missing header, Contact details

---

app/views/admin/management/show.html.haml
app/views/admin/person_uploads/new.html.haml

https://dsdmoj.atlassian.net/browse/PFT-377

Management page: template upgrade

---

spec/features/person_maintenance_spec.rb
spec/support/pages/edit_profile.rb
spec/support/pages/new_profile.rb
spec/support/pages/sections/error_summary.rb
spec/support/pages/sections/profile_form.rb

spec fixes in line with govuk_element_form_builder changes - specifically error handling.

fix person_maintenace_spec inline with template updates

---

app/assets/javascripts/application.js
app/assets/javascripts/modules/moj.Helpers.js
app/assets/javascripts/modules/moj.Module.search.js

https://dsdmoj.atlassian.net/browse/PFT-388

Profile page: Radio buttons init

---

app/assets/stylesheets/application-ie8.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/elements-local/_typography.scss
app/assets/stylesheets/modules/_module-media.scss

https://dsdmoj.atlassian.net/browse/PFT-407

PFT-407: IE8 fixes

---

app/controllers/people_controller.rb

role section disappearing when a create action
fails with validation errors.

fix role section disappearing

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_module-complete-indicator.scss
app/views/people/_completeness.html.haml

https://dsdmoj.atlassian.net/browse/PFT-412

Profile page: completeness

---

spec/features/group_maintenance_spec.rb

.spec/features/group_maintenance_spec.rb increasingly flcikering
since gem updates.

skip flickering test

---

app/views/people/_form.html.haml
app/views/person_image/edit.html.haml

inconsistent use of picture, photo and profile photo
etc is not user friendly. requested by User researcher

change content for photo uploading feature

---

app/views/people/_form.html.haml

Missed from previous commit. UR/PM agreed on change.

change label for profile image to profile photo

---

app/models/person_upload.rb
app/views/admin/person_uploads/new.html.haml
spec/features/csv_upload_spec.rb
spec/models/person_upload_spec.rb

prevent uploading of non-CSV files to bulk uploader.

validate the mime type of the uploaded csv file

---

app/views/person_image/edit.html.haml

https://dsdmoj.atlassian.net/browse/PFT-442
Why are we doing this?
To give better guidance when users upload a picture
Updates the copy for the guidance steps

Photo - change guidance

---

config/kubernetes/development/deployment.yaml

I expect this to change quite a bit, but perhaps it's OK to start. I guess we shouldn't merge until we have fixed issues on the ping and healthcheck.

Ct 2663 readiness and liveness probe

---

app/views/home/show.html.haml
app/views/layouts/_survey_banner.html.haml
app/views/people/show.html.haml
app/views/search/index.html.haml

Preparation work for CP migration of PF, will require some downtime, warn users with this banner copied and adjusted to suit. This will be removed once migration is complete, so not perfect code.
https://dsdmoj.atlassian.net/browse/CT-2713
n/a
Use the app - view the banner where it appears on home page, search results page, and Person profile page

CT-2713 Temporary banner for maintenance, throw away code

---

.circleci/config.yml
Dockerfile

Notes:
Add username to circle ci Slack
Disable Docker Layer Caching to save 200 credits per run since it only takes 7 odd mins anyway to build, this was discovered during the ticket process. Caching will take some time & effort, not really worth it. 
https://dsdmoj.atlassian.net/browse/CT-3139
Deploy using Circle CI
Make sure that build is fast at least 2nd time round if bundle/dockerfile not changed

CT-3139 Dockerfile, caching and Slack username

---

README.md

Add a way to get past token authentication without Email to the readme file

Add tip to get past token authentication

---

Dockerfile
Gemfile
Gemfile.lock
run.sh

Change Dockerfile to use Alpine, a per Contact MOJ and Track-a-query.
Can test here: https://development.peoplefinder.service.gov.uk/
(Truncated - 25 critical, 170+ hight, 483 medium, 346 low)
After:
https://dsdmoj.atlassian.net/browse/CT-3538
full test needed
full regression test

CT-3538 shrink dockerfile and change to alpine

---

.circleci/config.yml
config/pipeline/aws_ecr_scan_results.py

Automate security scanning as per Track-a-query and Contact MOJ
No issues so no Slack message
https://dsdmoj.atlassian.net/browse/CT-3539
deployment test as part of this
Regression test app

CT-3539 Automate security scanning

---

Gemfile.lock

Dependabot updates
https://dsdmoj.atlassian.net/browse/CT-3655
n/a
Regression test only

Ct 3655 dependabot updates

---

Gemfile
Gemfile.lock

This is inline with best practice as per:
https://github.com/ddollar/foreman/wiki/Don't-Bundle-Foreman
[CT-3646](https://dsdmoj.atlassian.net/browse/CT-3646)

Remove foreman from gemfile

---

.circleci/config.yml
build.sh
config/kubernetes/production/cronjob-delete-old-ecr-images.yaml
deploy.sh

Update references from master to main
[CT-3627](https://dsdmoj.atlassian.net/browse/CT-3627)

CT-3627 Update references from master to main

---

config/kubernetes/demo/deployment.yaml
config/kubernetes/demo/env-configmap.yaml
config/kubernetes/development/deployment.yaml
config/kubernetes/development/env-configmap.yaml
config/kubernetes/production/cron-never-logged-in-notifier.yaml
config/kubernetes/production/cron-person-notifier.yaml
config/kubernetes/production/cron-person-update-reminder.yaml
config/kubernetes/production/cron-photo-profiles-report.yaml
config/kubernetes/production/cron-profile-changed-report.yaml
config/kubernetes/production/cron-profile-completions-report.yaml
config/kubernetes/production/cron-profile-percentage-report.yaml
config/kubernetes/production/cron-team-description-notifier.yaml
config/kubernetes/production/cron-total-profiles-report.yaml
config/kubernetes/production/cron-user-behaviour-report.yaml
config/kubernetes/production/deployment.yaml
config/kubernetes/production/env-configmap.yaml
config/kubernetes/staging/deployment.yaml
config/kubernetes/staging/env-configmap.yaml

Dry out environment variables across deployments and cronjobs
https://dsdmoj.atlassian.net/browse/CT-3555
needs testing on all envs
minimal regression

CT-3555 Dry out environmental variables

---

app/controllers/suggestions_controller.rb
config/brakeman.ignore
spec/controllers/suggestions_controller_spec.rb

Fixes / makes exceptions for issues seen by brakeman. Discussions of actions taken in commit messages. Also see the spreadsheet on the card with which also explains reasoning.
[CT-3691](https://dsdmoj.atlassian.net/browse/CT-3691)
- please have a look at my reasoning for these opt outs / mitigations.

CT-3691 breakman issues

---

.circleci/config.yml
Gemfile
Gemfile.lock
spec/rails_helper.rb

This PR is to remove the old codeclimate gem,  install the new test reporter
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&modal=detail&selectedIssue=CT-3640

CT-3640 Removed the old codeclimate gem and installed the new test report

---

config/application.rb

This PR is to fix the sentry error of not finding GeckoboardPublisher,  it affects 5 cronjobs for publishing reports
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=25&modal=detail&selectedIssue=CT-3884&sprint=2320

CT-3884 added"geckoboard" lib path for report cronjobs

---

db/seeds/data/permitted_domains.yml

Add CCRC non-gsi domain to permitted list
https://dsdmoj.atlassian.net/browse/CT-3966

CT-3966 Add CCRC domain

---

.circleci/config.yml
db/seeds/data/permitted_domains.yml

CT-4006 Add ima domain

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/development/ingress.yaml
deploy.sh

Migration to live 
https://dsdmoj.atlassian.net/browse/CT-3969
Interim stage - will change when all namespaces are migrated. Requires live context login if done manually.

Ct 3969 Migrate to live (EKS)

---

config/kubernetes/development/ingress-live.yaml
config/kubernetes/development/ingress.yaml

Route ingress traffic to live cluster
https://dsdmoj.atlassian.net/browse/CT-3969

CT-3969-development Reroute ingress to live

---

config/kubernetes/staging/ingress-live.yaml
config/kubernetes/staging/ingress.yaml
deploy.sh

This PR is to add the ingress files and change the steps in deploy.sh for EKS migration
https://dsdmoj.atlassian.net/jira/software/c/projects/CT/boards/25?modal=detail&selectedIssue=CT-3969

CT-3969 EKS migration for staging env

---

config/kubernetes/demo/deployment.yaml
config/kubernetes/demo/ingress-live.yaml
config/kubernetes/demo/ingress.yaml
deploy.sh

Migrate live 1 to live
[](https://dsdmoj.atlassian.net/browse/CT-3969)
This is mainly for live, live1 is dying thanks to Elastic search being old
Deploy on Circle ci

Ct 3969 demo migrate live1 to live

---

config/kubernetes/production/ingress-live.yaml
deploy.sh

https://dsdmoj.atlassian.net/browse/CT-3969

EKS migration for production env

---

app/assets/javascripts/modules/moj.Module.loadtime.js

Roll out same script as CT to get Load Time Metric working on GA. (Based on this: https://github.com/ministryofjustice/correspondence_tool_staff/pull/1818)
n/a
https://dsdmoj.atlassian.net/browse/CT-4019
nothing really
Check GA once on Dev and go to Realtime > Event tracking

CT-4019 Add page load time metric

---

config/kubernetes/demo/ingress-live.yaml
config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

Add default modsecurity to application

Add default modsecurity

---

config/kubernetes/demo/ingress-live.yaml
config/kubernetes/development/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

Reverts ministryofjustice/peoplefinder#767

Revert "Add default modsecurity"

---

db/seeds/data/permitted_domains.yml

Add non-GSI YJB email to allowed domains list
https://dsdmoj.atlassian.net/browse/CDPT-162

CDPT-162 Add YJB non-gsi email

---

config/kubernetes/demo/ingress-live.yaml
config/kubernetes/production/ingress-live.yaml
config/kubernetes/staging/ingress-live.yaml

ingress controller updated

---

.env.example
README.md
app/assets/javascripts/modules/moj.Module.loadtime.js
app/views/layouts/_ga.html.haml
app/views/layouts/application.html.haml
config/application.rb
config/kubernetes/demo/env-configmap.yaml
config/kubernetes/development/env-configmap.yaml
config/kubernetes/production/env-configmap.yaml
config/kubernetes/staging/env-configmap.yaml
public/400.html
public/401.html
public/403.html
public/404.html
public/405.html
public/406.html
public/408.html
public/411.html
public/413.html
public/415.html
public/416.html
public/422.html
public/423.html
public/424.html
public/500.html
public/501.html
public/504.html
public/nginx/500.html
public/nginx/505.html

CDPT-215 Setup GA4 and keep GA3 running
https://dsdmoj.atlassian.net/browse/CDPT-215

CDPT-215 Setup GA4 and keep GA3 running

---

config/kubernetes/development/ingress-live.yaml

Fix development namespace ingress to work with cluster update

Fix development namespace ingress to work with cluster update

---

app/controllers/people_controller.rb
app/models/person.rb
app/views/people/_form.html.haml
app/views/people/_profile.html.haml
config/locales/en.yml
db/migrate/20221215113851_add_swap_email_display_to_people.rb
db/schema.rb
spec/models/person_spec.rb

CDPT-434 Allow secondary email to display as main email

---

README.md

CDPT-475 Update readme with latest Elastic search info
https://dsdmoj.atlassian.net/browse/CDPT-475

CDPT-475 Update readme with latest Elastic search info

---

app/models/token.rb
spec/models/token_spec.rb
spec/services/token_login_spec.rb

To handle emails being scanned and causing tokens to be spent, we are enabling a 10 minute validity period which will allow tokens to work an unlimited amount of time during the first 10 minutes.

CDPT-448 Enable token validity period in Production

---

.circleci/config.yml
Gemfile
README.md

Updates docker image for Postgres used for tests. No longer uses deprecated image, and uses the correct version of Postgres.
Also updates README for correct Ruby version, and sets Ruby version in Gemfile from .ruby-version so it won't have to be updated again.

Update test postgres version

---

Gemfile.lock

There is an issue using latest bundler versions when deploying

Use older bundler version

---

.circleci/config.yml

Use short lived credentials to connect to ECR

CDPT-764 Use short lived credentials

---

.circleci/config.yml
spec/presenters/audit_version_presenter_spec.rb
spec/services/suggestion_delivery_spec.rb

Adds in ENV vars to be shown on ping.json page.
Also fixes a couple of rubocop comment issues.

Pass env vars to docker image and fix build tag

---

db/seeds/data/permitted_domains.yml

https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-844

add hmiprobation.gov.uk domain

---

README.md

Added a step by step guide on how to add a new domain to PF allowed emails.
No ticket for this.

Update instructions when adding a new email domain to the live DB

---

config/initializers/sentry.rb

Large amounts of issues are being logged from the Development environment which are taking up unnecessary budget.

CDPT-978 Don't log to Sentry in dev and test

---

.circleci/config.yml
Gemfile
config/brakeman.ignore

Add Brakeman static vulnerability scanner to CircleCI build
https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?modal=detail&selectedIssue=CDPT-872

Add Brakeman to CI pipeline

---

Gemfile
Gemfile.lock
spec/rails_helper.rb

Use updated selenium-webdriver to manage correct chromedriver version which is no longer supported by webdrivers

Remove webdrivers

---

.circleci/config.yml

- Replaces deprecated image
- Fixes build tag for when branch name has slashes

CDPT-1422 Replace image

---

app/services/health_check_service.rb
spec/services/health_check_service_spec.rb

Fix healthcheck exception

---

app/models/health_check/database.rb
spec/features/application_health_check_spec.rb
spec/models/health_check/database_spec.rb

Update database healthcheck to use simple query

Use simple query to check database

---

.github/workflows/deploy.yml
.github/workflows/test.yml
Dockerfile
config/database.yml

https://dsdmoj.atlassian.net/jira/software/c/projects/CDPT/boards/1152?selectedIssue=CDPT-1216

Switch from CircleCI to Github actions

---

.github/workflows/deploy.yml
build.sh
config/kubernetes/development/deployment.yaml
config/kubernetes/production/cron-never-logged-in-notifier.yaml
config/kubernetes/production/cron-person-notifier.yaml
config/kubernetes/production/cron-person-update-reminder.yaml
config/kubernetes/production/cron-team-description-notifier.yaml
config/kubernetes/production/cron-user-behaviour-report.yaml
config/kubernetes/production/deployment.yaml
config/kubernetes/staging/deployment.yaml
deploy.sh

- Remove "-ecr" from the image name
- Update deployment webapp and jobs to use latest image

Update image name, deployment metrics and jobs

---

config/kubernetes/development/deployment.yaml
config/kubernetes/production/deployment.yaml
config/kubernetes/staging/deployment.yaml

Deployment syntax fix

---

.github/workflows/deploy.yml

Add production release slack message

---

.github/workflows/test.yml

Deploy postgres:16-alpine image to test database for upgrade dry run
https://dsdmoj.atlassian.net/browse/CDPT-1819

CDPT-1819: PF-Deploy postgres alpine image to test db

---

.env
README.md
config/application.rb

There have been 2 IP restriction lists. One for read only users, and one for admins. To simplify things, and as it is not considered a security risk there will now be one IP allowlist.

Merge IP lists

---

README.md
config/application.rb

Revert name change of variable

Fix variable name

---

Dockerfile

Replacing imagemagick with graphicsmagick as that appears to work better. Previously they were both included in the Dockerfile.

Fix profile photo upload

---

.github/workflows/deploy.yml

Fix deploy script to use the correct names

Fix cronjob names

---

.github/workflows/deploy.yml

There are unique values for each namespace.

add env vars for each environment

---

app/views/search/_person.html.haml

A score is shown against every search result in development environments and in production to super admins.
This is no longer required.

Remove search score

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/views/layouts/govuk_template.html.erb
config/environments/test.rb
config/locales/en.yml
spec/rails_helper.rb
spec/spec_helper.rb

Add a link below the header to a user survey
https://dsdmoj.atlassian.net/browse/CDPT-2645

CDPT-2645 Create feedback link
