db/migrate/20150210115300_detoxify_yaml.rb
* Don't try to correct new versions created after the code changed, i.e.
where the image is already a string
* Fix the 'object' field as well, which also contained broken YAML.
* Don't try to fix blank YAML: if the event is destroy, then object_changes
is nil.
=> Make the version YAML fix more robust

app/controllers/peoplefinder/application_controller.rb, app/models/peoplefinder/group.rb, app/models/peoplefinder/membership.rb, app/models/peoplefinder/person.rb, app/models/peoplefinder/version.rb, app/presenters/peoplefinder/audit_version_presenter.rb, app/views/peoplefinder/people/_audit.html.haml, db/migrate/20150211153741_add_ip_address_to_versions.rb, db/migrate/20150211164821_add_user_agent_to_versions.rb, peoplefinder.gemspec, spec/dummy/db/schema.rb, spec/features/person_audit_spec.rb, spec/features/person_maintenance_spec.rb, spec/models/peoplefinder/version_spec.rb
> As a member of the People Finder Product team I want to be able to accurately identify who is making changes to the content or structure of the People Finder product so that I can take appropriate action when errors occur [(Trello)](https://trello.com/c/9pR3N0bK/181-m-as-a-member-of-the-people-finder-product-team-i-want-to-be-able-to-accurately-identify-who-is-making-changes-to-the-content-or)
* Store the ID of the person, and link to them from the audit log
* Record their IP address
* Record browser details
The [useragent](https://github.com/josh/useragent) gem is used to reduce raw user agent strings down to a simple and easy-to-read form in the audit log, though the full string is still available on hover via the `title` attribute.
Old version records where the user was stored as a …
=> Record and show more information about people who make changes

app/models/peoplefinder/person.rb, spec/models/peoplefinder/person_spec.rb
This is a fix for already existing uniqueness validation.
=> Make email uniqueness validation case insensitive

.rubocop.yml, app/models/peoplefinder/email_address.rb, spec/models/peoplefinder/email_address_spec.rb
I don't like that the definition of `valid_email_address?` creates an instance of the superclass here and uses that for validation, but I couldn't see an easy way around it. Rubocop is giving me a cyclomatic complexity error and I suspect this is the reason why.
One option would be to break format validation into it's own separate thing. Thoughts? @threedaymonk
=> Accept emails with apostrophe

app/helpers/peoplefinder/application_helper.rb, app/views/peoplefinder/people/_form.html.haml, app/views/peoplefinder/shared/_editing_alert.html.haml, config/locales/en.yml
By using concatenation on a SafeBuffer and `_html` suffixes on keys for translations containing HTML, we make two occurrences of `html_safe` unnecessary.
Fixes #44.
=> Eliminate unnecessary use of html_safe

app/views/peoplefinder/groups/_subgroup.html.haml
The description is visually truncated, but we don't want to send an excessive amount of text that no one will see. The solution chosen is to truncate the description at a reasonable point that is nonetheless longer than will be displayed. After experimentation, 350 characters seems to work well.
=> Truncate subteam description on index page

app/assets/stylesheets/peoplefinder/groups.css.scss
=> Removes the fadeout at the bottom of Subgroups whilst tabbing through

app/helpers/peoplefinder/application_helper.rb, app/models/peoplefinder/person.rb, app/views/layouts/peoplefinder/_shared.html.haml, app/views/peoplefinder/people/_person.html.haml, app/views/peoplefinder/people/show.html.haml, spec/helpers/peoplefinder/application_helper_spec.rb
Mark up telephone numbers with `<a href="tel:…">…</a>` so that you can touch to dial on mobile devices (or anything else that supports the `tel:` scheme).
=> Mobile actions

app/controllers/peoplefinder/metrics/completions_controller.rb, app/models/peoplefinder/concerns/completion.rb, config/routes.rb, spec/controllers/peoplefinder/metrics/completions_controller_spec.rb, spec/factories.rb, spec/models/peoplefinder/concerns/completion_spec.rb
This calculates the overall completion score across all profiles and exposes it via a Geckoboard-compatible endpoint at `/metrics/completions`.
=> Expose a simple API so we can show overall completion on Geckoboard

app/models/peoplefinder/token.rb, spec/features/token_authentication_spec.rb, spec/models/peoplefinder/tokens_spec.rb
Some users add spaces to their emails when trying to log in, for reasons unknown (possibly copy and paste). This lets them log in instead of hectoring them with unhelpful error messages.
=> Strip spaces around email when logging in

app/controllers/peoplefinder/groups_controller.rb, app/controllers/peoplefinder/people_controller.rb, app/helpers/peoplefinder/application_helper.rb, app/mailers/peoplefinder/group_update_mailer.rb, app/models/peoplefinder/group.rb, app/models/peoplefinder/membership.rb, app/services/peoplefinder/group_update_service.rb, app/views/peoplefinder/group_update_mailer/inform_subscriber.erb, app/views/peoplefinder/people/_membership_fields.html.haml, config/locales/en.yml, db/migrate/20150304110649_add_subscribed_to_membership.rb, spec/dummy/db/structure.sql, spec/features/group_maintenance_spec.rb, spec/features/person_membership_spec.rb, spec/helpers/peoplefinder/application_helper_spec.rb, spec/mailers/peoplefinder/group_update_mailer_spec.rb, spec/models/peoplefinder/group_spec.rb, spec/models/peoplefinder/membership_spec.rb, spec/services/peoplefinder/group_update_service_spec.rb
Adds a checkbox on the profile edit page, when editing the team, to (un)subscribe the person to/from email notifications when the team changes.
Email copy is just a placeholder, and yet to be confirmed.
=> Team subscriptions

app/views/peoplefinder/people/show.html.haml
Fixes the layout for the Permanent Secretary.
=> Don't show team label if team is top level

app/models/peoplefinder/concerns/placeholder.rb, app/models/peoplefinder/group.rb, app/views/peoplefinder/groups/_detail.html.haml, app/views/peoplefinder/groups/_form.html.haml, app/views/peoplefinder/groups/_subgroup.html.haml, config/locales/en.yml, spec/models/peoplefinder/concerns/placeholder_spec.rb
* When editing, the placeholder text is displayed in an empty textarea via the placeholder HTML attribute.
* When viewing, the placeholder is shown instead of the description if the description is blank.
=> Show default placeholder for team description

app/assets/stylesheets/peoplefinder/application.scss, app/views/peoplefinder/groups/_detail.html.haml, app/views/peoplefinder/groups/_subgroup.html.haml
The navigation bar was made weird by the additional indentation. We only need the styling within formatted text that's being generated via Markdown, so we'll wrap it in a formatted-text class and apply the style only within that.
=> Style lists only within a container

db/seeds.rb, db/seeds/data/permitted_domains.yml, db/seeds/permitted_domains.rb
Hi @threedaymonk, this adds the domains we're currently using to validate email addresses to the database when you run `rake db:seed` as discussed.
I need to merge this and get Kyriakos to run `rake db:seed` on production before we can actually add the code that checks against these rather than read the domains out of config.
=> Adds default permitted domains on rake db:seed

app/models/group.rb, app/services/group_lister.rb, app/views/people/_membership_fields.html.haml, spec/services/group_lister_spec.rb
Fixes #109 by building an array of lightweight objects from a single query.
=> Make group selector database-efficient

app/uploaders/image_uploader.rb
Because we've changed the model namespace (from `Peoplefinder::Person` to `Person`), the implicitly-computed upload paths have changed and all the old pictures don't work.
I'd rather have the directory set explicitly for each model, rather than relying on the class name, but this is a quick fix for the immediate problem.
=> Use the same upload path as in the engine era

app/models/concerns/completion.rb, spec/models/concerns/completion_spec.rb
As a user I don't want to have to add Extra Info to my profile in order for it to be judged to be 100% complete
Trello #282
=> Exclude extra information from completeness calculation

config/routes.rb
We'd rather do this at the server level, so this is a temporary fix until server configuration is changed.
=> Restrict admin to known IP addresses

app/controllers/groups_controller.rb, lib/tasks/brakeman.rake
Although Brakeman is not perfect – it won't identify every vulnerability, and not everything it complains about is necessarily a problem – having no warnings is a reasonable goal. Although we already had Brakeman in the Gemfile, it wasn't necessarily being used.
This changeset, therefore:
1. Adds Brakeman to the standard Rake task, and makes the build fail if Brakeman identifies any potential vulnerabilities.
2. Addresses things that Brakeman complains about, so that the build will still pass.
=> Run Brakeman as part of default CI task

app/models/person_upload.rb, app/services/csv_people_importer.rb, app/services/email_extractor.rb, app/services/person_csv_importer.rb, app/services/person_csv_parser.rb, lib/tasks/peoplefinder/import.rake, spec/models/person_upload_spec.rb, spec/services/csv_people_importer_spec.rb, spec/services/email_extractor_spec.rb, spec/services/person_csv_importer_spec.rb, spec/services/person_csv_parser_spec.rb
[Story 330](https://trello.com/c/j94heRWK/330-s-take-outlook-output-contact-list-in-format-surname-name-name-surname-domain-com-and-rationalise)
The CSV files generated from the Global Address List look something like:
```
First Name,Last Name,E-mail Display Name
Reinhold,Denesik,"Denesik, Reinhold (Reinhold.Denesik@valid.gov.uk)"
Lelah,Jerde,"Jerde, Lelah (Lelah.Jerde@valid.gov.uk)"
```
… which doesn't conform to our stated schema, but is still systematic enough that we could parse it.
First, we change CSV parsing to treat column names more liberally. Specifically, case is ignored, and:
* The column for `given_name` can be called anything containing 'first' or 'given';
* The column for `surname` can be anything containing 'surname', 'family', or 'last';
* The column for `email` can be …
=> Make CSV parsing (for bulk upload) more liberal

app/assets/stylesheets/peoplefinder/groups.css.scss, app/assets/stylesheets/peoplefinder/maginot.scss, app/assets/stylesheets/peoplefinder/people.css.scss, app/helpers/people_helper.rb
[Story 337](https://trello.com/c/X5doZMQ7/337)
This puts in front of all profile images a div of the same width and height, preventing the most unskilled users from saving the image via a right click or by dragging it out of the browser.
This is, of course, ultimately futile: even six-year-olds know how to get around this, and print screen will still work.
=> 'Stop' people downloading photos

app/assets/javascripts/application.js, app/controllers/pages_controller.rb, app/views/layouts/application.html.haml, app/views/pages/show.html.haml, config/locales/en.yml, config/locales/pages.en.yml, config/routes.rb, spec/features/cookie_message_spec.rb
This uses the existing cookie banner from the template: on first visit, a banner is shown, with a link to the policy. On subsequent visits, the banner is not shown.
=> Add a cookie message and policy

app/models/token.rb
When using Heroku we noticed that as 'max_tokens_per_hour' was being defined as a String, a type error was thrown.
Here I cast the type to an integer at first point of reference.
=> ENV value no longer errors out when String

config/initializers/assets.rb
The precompilation path for Jcrop was incorrect. This broke the photo cropping interstitial page, but in a way which is not caught in the test environment.
=> Fix photo uploads

config/initializers/carrierwave.rb
Fog changed to using AWS V4, and can't guess the correct region any more. This leads to error messages from S3 like:
> The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'eu-west-1'
As a fix, we will specify the region explicitly via the S3_REGION environment variable.
See https://github.com/fog/fog/issues/3275
=> Specify S3 region explicitly

app/assets/stylesheets/peoplefinder/people.css.scss
Because '100%' is wider than '99%', the text didn't fit properly once we started showing the box at 100% to congratulate people.
Making the box the same width as the profile photo above looks more consistent and fixes the wrapping.
=> Fix weird wrapping at 100% complete

app/views/layouts/email.html.erb, smoke_test
Tweaking the retries for both Token request and Fetch email token
=> Allow a buffer of time/retries between the DNS based maintenance page being switched off and the smoke tests testing the site

spec/features/report_a_problem_spec.rb
The particular time chosen for these specs happens to be 57 seconds past the minute, which gives the spec three seconds to run before the minute matched in the assertion fails.
This is not usually a problem, but Travis CI sometimes runs very slowly indeed. Changing the start time to the top of the minute gives us a whole 60 seconds of oxygen.
Freezing time for the duration of the spec would be a simpler solution, but, alas, "Capybara does not work with libraries which freeze time".
=> Fix unreliable specs

app/models/health_check/database.rb, config/database.yml, spec/models/health_check/database_spec.rb
The motivation for this is that #154 broke my ability to run the test suite without tweaking the database configuration each time.
The configuration is now reported by the health check regardless of whether host/database or URL configuration is used, i.e. it works with any configuration supported by Rails. This means that the test configuration no longer has to be a URL.
If `DB_TEST_URL` is defined, it will still be used in the `test` environment; if not, the previous configuration of `database: peoplefinder_test` is used: this works with PostgreSQL peer authentication.
=> Make health check database details flexible

app/models/health_check/database.rb, app/models/health_check/database_configuration.rb, spec/models/health_check/database_configuration_spec.rb
A database URL can (and, where it matters, usually will) contain the database password. We should never expose this in the healthcheck.
Instead, we now extract fields from the configuration hash and, optionally, the url field in the hash, and return only whitelisted parameters
=> Never expose DB password in healthcheck

app/controllers/search_controller.rb, app/services/person_search.rb, app/views/shared/_search.html.haml, spec/controllers/search_controller_spec.rb, spec/services/person_search_spec.rb
When percent-encoded invalid UTF-8 was passed via the query parameter, an exception was raised, and a 500 status resulted.
This happened because, although the invalid UTF-8 was safe at rest, as soon as it was used to generate the JSON to be sent to Elasticsearch, an encoding error was raised. This masked a secondary problem where the parameter was interpolated into the view, which would also have caused
an encoding error.
Instead, we now validate the encoding in the controller (by attempting to convert the UTF-8 to UTF-32LE) and replace it with an empty string if it's not valid. The valid query or empty string is assigned to an instance variable for use in the view.
=> Stop generating errors on invalid search input

app/models/group.rb, app/models/person.rb, db/migrate/20150604110007_remove_invalid_relationships.rb, db/migrate/20150604110654_enforce_membership_integrity.rb, db/seeds/permitted_domains.rb, db/structure.sql
It should not be the case that a `Membership` exists separately from either a `Person` or a `Group`. Nonetheless, this was the case on staging after penetration testing. This situation manifested as a 500 error; the real problem was that a `nil` `Group` was not expected. The `Membership` referred to a `Group` that had been deleted, but nothing cascaded the deletion to the `Membership`, and there was no database-level enforcement of consistency.
The fix is in three parts:
1. Delete any orphaned `memberships` from the database.
2. Add `NOT NULL` and foreign key constraints to ensure that orphaned memberships cannot exist in future.
3. Add the missing `dependent: :destroy` on `Membership` to ensure that deleting a group will delete its membership.
=> Prevent orphaned memberships

app/mailers/user_update_mailer.rb, app/services/person_destroyer.rb, app/views/user_update_mailer/deleted_profile_email.html.erb, spec/features/person_maintenance_spec.rb, spec/services/person_destroyer_spec.rb
Previously, we pushed the user ID to the queue. Within the transaction of the test environment, this works. In the wild, the queue is consumed in a different context, in which the user no longer exists.
We can delete the defective queue entries after deploying this.
=> Enqueue all data needed to email deleted user

app/assets/stylesheets/peoplefinder/application.scss, app/views/tokens/create.html.haml, config/locales/en.yml, spec/features/token_authentication_spec.rb
After the user enters their email address, a login token is generated and sent
to the user via email. The next page has a bit of informative text prompting the
user to check their emails for a login token.
This page used to look like an error message or a broken page rather than an
important piece of information. We've styled the page and changed the copy to
make it more appealing and hopefully it will be ignored less.
=> A more helpful login prompt

app/assets/javascripts/peoplefinder/photo_upload.js, app/controllers/people_controller.rb, app/helpers/people_helper.rb, app/models/person.rb, app/uploaders/image_uploader.rb, spec/models/person_spec.rb, spec/models/profile_photo_spec.rb, spec/support/profile.rb, spec/uploaders/image_uploader_spec.rb
With the merge of #139, profile photos are now stored against a separate object. This poses a problem for all the existing photos, because the path is dynamically generated by CarrierWave based on class and ID. It's not trivial to move all the objects in S3, nor to change CarrierWave to a more (how shall we say?) forward-thinking path strategy.
Instead, we'll continue to mount the image uploader on the Person as before, and return it for `profile_image` only if there is not an associated profile photo object.
=> Make legacy profile images continue to work

Gemfile, Gemfile.lock, app/uploaders/image_uploader.rb
https://github.com/DarthSim/carrierwave-bombshelter was one of the
CarrierWave recommended solutions to the problem of image bombs. After a
quick review of it and the supporting FastImage gem, I decided that
using it was more sensible than trying to roll the same thing from
scratch.
This commit also include the fast-failing rspec formatter Fuubar and an
update to rspec.
=> Use Bombshelter to prevent image size DoS attack

app/controllers/tokens_controller.rb, lib/secure.rb, spec/controllers/tokens_controller_spec.rb, spec/lib/secure_spec.rb
Ideally, this would have been implemented using Devise.secure_compare.
However, peoplefinder does not use Devise, so I decided to port the
logic and tests of that method into the app directly.  I also added a
controller spec for the the tokens_controller to ensure that it was
working end-to-end.
I am not entirely happy with my use of Token.find_each to locate the
correct token.  That said, it appeared to be cleanest way to implement
the lookup from a conceptual standpoint. I considered sorting the tokens
and then starting the find_each at the appropriate point in the recored
set. However, doing so seemed like premature optimisation at this
point.
=> Fix vulnerability to cryptographic timing attacks

Gemfile, Gemfile.lock
With the CODECLIMATE_REPO_TOKEN set.  I've already set this in circleci,
so it should just work.
=> Enables codeclimate coverage tracking

app/controllers/tokens_controller.rb, spec/features/token_authentication_spec.rb, spec/features/token_user_email_shared.rb
The original pentest flagged a possible vulnerability regarding an
attacker brute-forcing the token authentication to ennumerate all of the
valid emails in the department.  It turns out this is not possible as
the token generator only checks for valid emails and valid domains.  It
is also rate-limited to 8 requests per hour. Nevertheless, after
discussions with our pentesters, I have disabled warnings regarding
invalid domains.
=> Prevent info leakage about invalid domains

app/controllers/tokens_controller.rb, spec/controllers/tokens_controller_spec.rb, spec/rails_helper.rb
The pentest recommended token expiry after use.  On review, it seemed more sensible to remove expired tokens.  I haven't made an exhaustive code review.  However, the token_controller creates a new one each time a login is requested and the old ones are never reused for token login.
The remedy for the cryptographic timing attack required a find_batch on all tokens.  Removing tokens as they are used keeps us from having to scope that find_batch to active tokens, setting up a cron job to remove expired tokens later, or just waiting for that find_batch to slow down due to the ever growing number of records.
=> Removes a token after use

README.md
Google moved everything around again, so a new list of 'click this', 'click that', 'click the other' is needed.
=> Update OAuth instructions

README.md
There were 2 sections completely missing - setting up permitted domains
and receiving e-mails in development environment.
=> Improve readme for development setup

app/models/token.rb, spec/features/token_authentication_spec.rb, spec/models/tokens_spec.rb, spec/rails_helper.rb
There wasn't any mechanism for removing old tokens.  This takes care of
that.  Spent tokens expire after three hours and are then deleted the
next time a new token is created.  It also raises an exception if the
TTL is reduced to less than hour as this would create a race condition
on the rate limiter.
=> Remove expired tokens when new tokens are created

README.md
Elasticsearch 2.0 has changes that break tests due to the `fuzzy_like_this` query being removed.
So elasticsearch needs to be fixed at 1.7 until we update our code.
=> Add Mac OSX install notes and specify elasticsearch 1.7

app/assets/stylesheets/peoplefinder/feedback.scss, app/controllers/problem_reports_controller.rb, app/views/shared/_feedback_form.html.haml, spec/features/report_a_problem_spec.rb
Add email field to feedback form when user logged out. Otherwise the user's email is unknown, and it is not possible to reply to the user.
=>  Add email field to feedback form

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, app/controllers/tokens_controller.rb, app/views/sessions/_login_page.html.haml, app/views/tokens/create.html.haml, config/locales/en.yml, spec/features/login_page_spec.rb, spec/support/pages/login.rb, spec/support/pages/token_created.rb, spec/support/permitted_domain_helper.rb
Slightly different copy is required for the login screen when the readonly user tries to edit something.
=> Change login copy for unauthorised actions

app/controllers/metrics/activations_controller.rb, app/models/concerns/acquisition.rb, app/models/concerns/activation.rb, app/models/person.rb, config/routes.rb, spec/controllers/metrics/activations_controller_spec.rb, spec/models/concerns/acquisition_spec.rb, spec/models/concerns/activation_spec.rb
We plan to remove the requirement for users to be logged in to use the people finder service. We hypothesise this may effect the % of users that log in and complete their profile.
This pull request adds actionable metrics we can monitor to see the impact of the coming changes:
`Acquisition` - represents the **% of profiles** where user has **logged in at least once**.
`Activation` - represents **% of acquired users** that have profile **completion score > 80%**.
These metrics are to help identify where the drop-offs are. Helps us answer questions: Are users never logging in? Are users failing to complete their profile when logged in?
Adds new controller action to return bullet graph JSON for display on geckoboard dashboard.
**Adds metric methods via concerns, following the approach used …
=> Acquisition and activation metrics

app/assets/javascripts/peoplefinder/autocomplete.js, app/views/people/_membership_fields.html.haml, config/locales/en.yml, spec/features/person_membership_spec.rb, spec/support/org_browser.rb
People need to understand the impact of clicking 'I am the leader of this team'.
On page load set the team name in the team leader checkbox to the current team selection.
When team selection changes set the new team name in the team leader checkbox hint text.
=> Change team leader checkbox text based on team selection

app/assets/stylesheets/peoplefinder/application.scss
Float grid-2-3 left at 980px instead of at 640px.
Fixes issue with photo image covering text on profile view and team view when screen width is between 640px and 980px.
=> Float grid-2-3 left when screen < 980px

app/models/concerns/completion.rb, spec/models/concerns/completion_spec.rb
This fixes bug where profiles with a legacy image attribute instead of a profile_photo could not reach a score of 100% complete. Previously these profiles could only reach a score of 88% complete.
=> Allow profile to be 100% complete when legacy image present

app/assets/stylesheets/peoplefinder/groups.css.scss, app/models/group.rb, app/views/groups/_subgroup.html.haml, spec/features/group_browsing_spec.rb, spec/models/group_spec.rb
Group completion_score is average of completion_score of all people in group.
Allows us to see how complete a team's members profiles are. Enables us to compare teams completeness. This is to encourage team members to complete their profile, and hence increase the team completion score.
If there are any performance problems after deployment to production, we will add to the backlog a ticket to periodically cache team completion score results.
=> Show subteam completion score on team view

app/models/person.rb, app/models/readonly_user.rb, app/views/people/_completeness.html.haml, app/views/people/_profile.html.haml, app/views/people/_request_information.html.haml, spec/features/person_maintenance_spec.rb, spec/models/person_spec.rb, spec/models/readonly_user_spec.rb
To encourage users to complete profiles, now show completion score to all users both logged in and not
logged in.
Edit link takes non-logged in users to login page.
=> Always show completion score and edit link on profile

app/controllers/profile_photos_controller.rb
This is a work around for an IE issue. Recent versions of IE treat the photo JSON returned as a file download, instead of passing it to the target iframe.
Tested in IE11 against staging environment.
=> Return photo JSON with text MIME type

spec/controllers/profile_photos_controller_spec.rb
To prevent fix for IE11 photo bug from being inadvertently removed.
=> Spec that photo response has MIME type set to "text"

app/assets/stylesheets/peoplefinder/groups.css.scss, app/controllers/groups_controller.rb, app/helpers/application_helper.rb, app/models/group.rb, app/models/person.rb, app/services/random_generator.rb, app/views/groups/people_outside_subteams.html.haml, app/views/groups/show.html.haml, config/routes.rb, spec/features/group_browsing_spec.rb, spec/helpers/application_helper_spec.rb, spec/models/group_spec.rb, spec/models/person_spec.rb, spec/services/random_generator_spec.rb
* Add link to "view people not assigned to sub-teams" on team view
* Show count of people in "view people" links
* New view shows people in team that are not assigned to a subteam
Potentially highlights incomplete data, as we expect most people to be assigned to a subteam. But in
live production data we are seeing a lot of people outside of subteams.
=> Show people outside of subteams

app/assets/stylesheets/peoplefinder/retinal_images.css.scss, app/models/group.rb, app/models/membership.rb, app/views/groups/_detail.html.haml, app/views/groups/_leadership.html.haml, app/views/groups/_leaderships.html.haml, app/views/people/_profile.html.haml, spec/features/person_membership_spec.rb, spec/models/group_spec.rb, spec/models/person_spec.rb
Remove the person, group uniqueness validation on memberships. Person is allowed to have multiple roles in the same team.
Fixes bug that prevented users with two roles on same team from saving edits to their profiles.
Only show person with two leadership roles once on team view.
=> Allow person with two roles in same team to save

app/models/email_address.rb, app/models/person.rb, app/models/token.rb, app/services/find_create_person.rb, app/validators/email_validator.rb, lib/tasks/peoplefinder.rake, spec/models/email_address_spec.rb, spec/models/person_spec.rb
- Remove redundant checks of email validity.
- Replace with checks that email has a domain matching list of configured permitted domains.
Email validity is checked when person is created or updated. So a person's email can always be considered valid. All invalid email addresses in legacy production data have been fixed.
=> Remove redundant checks of email validity

app/services/person_search.rb, spec/services/person_search_spec.rb
To increase likelihood of an exact name match appearing higher in search results list, put non-fuzzy search results ahead of fuzzy search results. Remove duplicates from final result list.
=> Combine non-fuzzy and fuzzy search results

app/models/health_check/elasticsearch.rb, spec/models/health_check/elasticsearch_spec.rb
Add elasticsearch cluster status check to healthcheck
The healthcheck for elasticsearch only checks that it can reach the
host at the moment. This change means that it will check if the host
is 'available', ie, can be reached, but also if it is 'accessible',
in that the cluster health is green.
* Update HealthCheck::Elasticsearch::available? to only check service is up
* Update HealthCheck::Elasticsearch::accessible? to check cluster health
* Update RSpec tests
=> Add elasticsearch cluster status check to healthcheck

Guardfile, app/services/person_search.rb, spec/services/person_search_spec.rb
Return empty array when search term is blank, instead of letting elasticsearch raise an exception.
=> Fix blank query bug

app/models/concerns/searchable.rb, app/services/person_search.rb, spec/services/person_search_spec.rb
Ensure exact name matches are at the top of search results.
=> Put exact name matches above synonym name matches

app/views/people/_person.html.haml, spec/views/people/_person.html.haml_spec.rb
Change to zero padded index so alphanumeric sorting in google analytics dashboard will order the event action text ascending by index number.
Also change event category text to "Search result click" for clarity.
=> Zero pad index in event action text

spec/features/application_health_check_spec.rb
Allow healthcheck spec to pass when development machine elasticsearch instance has a non-green cluster status.
=> Mock elasticsearch status in healthcheck spec

app/assets/javascripts/analytics/virtual_pageview.coffee, app/views/people/_person.html.haml, spec/javascripts/analytics/virtual_pageview_spec.coffee, spec/views/people/_person.html.haml_spec.rb
In order to setup a goal funnel where we can confirm a link has been clicked, send a `/search-result` pageview to google analytics, in addition to the `/top-3-search-result` or `/below-top-3-search-result` pageview.
=> Send two virtual pageviews on search result click

app/views/people/_person.html.haml, spec/views/people/_person.html.haml_spec.rb
In order for team link clicks to appear in google analytics goal funnel, send virtual pageview when team link in search results list is clicked.
=> Send virtual pageview when team link in results clicked

app/helpers/application_helper.rb, app/views/people/_person.html.haml, spec/views/people/_person.html.haml_spec.rb
Send analytics event and virtual pageviews when team or email link in search results is clicked. This matches the analytics sent when the person link is clicked in search results.
=> Send analytics when team or email link clicked

app/controllers/search_controller.rb, app/services/person_search.rb, spec/controllers/search_controller_spec.rb, spec/services/person_search_spec.rb
This improves search result relevance when searching via elasticsearch.
=> Strip commas from search query

.rubocop.yml, app/controllers/tokens_controller.rb, app/services/token_sender.rb, app/views/sessions/_login_page.html.haml, spec/models/token_spec.rb, spec/services/token_sender_spec.rb
When user requests a login token email, and has an active token, then send the same token value in the login email.
Ensure token throttle limit is respected when sending token email by always creating a new token even when we resend the same token value.
Move token sending logic out of the controller and into a service object.
=> Resend active token value

app/services/token_sender.rb, circle.yml, spec/features/token_authentication_spec.rb, spec/services/token_sender_spec.rb
Ensure clicking login link in email results in the right token being found. Change value on old token when sending new token with the same value. Means only the new token is found when searching for the token value.
Add spec that when user requests a login token a second time within 3 hours of the previous request, send the same token url.
Add spec that when user requests a login token a second time 3 hours after the previous request, send a different token url.
=> Ensure login works for second login token email sent within 3 hours

app/models/token.rb, app/services/token_sender.rb, spec/models/token_spec.rb, spec/services/token_sender_spec.rb
Look for unspent user token. Fixes bug where spent token was found, resulting in user receiving a new token value instead of being resent active token value.
=> Search only for unspent user token in token_sender 

app/models/concerns/sanitizable.rb, app/models/person.rb, spec/factories.rb, spec/models/concerns/sanitizable_spec.rb, spec/models/person_spec.rb, spec/services/person_csv_importer_spec.rb
Ensure that digits are stripped from names during the import process, as in some cases names have been generated from email addresses that containing a digit in the surname.
=> Strip digits from names before validating person

app/controllers/search_controller.rb, app/services/person_search.rb, spec/controllers/search_controller_spec.rb, spec/models/person_spec.rb, spec/services/person_search_spec.rb
When exact email match for query, return that person as the sole search result.
=> Allow search by email address

Guardfile, app/mailers/only_send_login_email_interceptor.rb, config/environments/production.rb, config/initializers/mail_interceptor.rb, spec/config/initializers/mail_interceptor_spec.rb, spec/mailers/only_send_login_email_interceptor_spec.rb
When `INTERCEPTED_EMAIL_RECIPIENT` env var is set, register mail interceptor which only sends login emails to real users and sends all other email to `INTERCEPTED_EMAIL_RECIPIENT`.
=> Enable staging env to only send login emails to real users

config/initializers/mail_interceptor.rb
Fixes bug where login email subject text is not found due to locales text not being loaded when mail interceptor initializer is run.
=> Ensure locales text loaded when configuring mail interceptor

Gemfile, Gemfile.lock, app/services/token_sender.rb, config/initializers/delayed_job.rb, spec/services/token_sender_spec.rb
- Require version of `delayed_job` that supports configuration of queue priorities.
- Configure a `:high_priority` queue with a higher priority than the default `:mailers` queue.
- Send login token emails via the `:high_priority` queue.
- Leave other emails to be sent via the default `:mailers` queue.
=> Configure login token emails to be higher priority than others

.rubocop.yml, Dockerfile, Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/controllers/people_controller.rb, app/mailers/reminder_mailer.rb, app/models/concerns/acquisition.rb, app/models/concerns/activation.rb, app/models/person.rb, app/services/login.rb, app/services/metrics_publisher.rb, app/services/never_logged_in_notifier.rb, app/views/reminder_mailer/never_logged_in.html.erb, config/application.rb, config/locales/en.yml, config/schedule.rb, db/migrate/20151217094046_add_last_reminder_email_at_to_people.rb, db/structure.sql, run.sh, spec/features/group_maintenance_spec.rb, spec/features/login_flow_spec.rb, spec/features/token_authentication_spec.rb, spec/mailers/reminder_mailer_spec.rb, spec/models/person_spec.rb, spec/services/login_spec.rb, spec/services/metrics_publisher_spec.rb, spec/services/never_logged_in_notifier_spec.rb
- Send reminder emails when users haven't logged in 30 days after being added to the system, and every 30 days after that if they have not logged in.
=> Send reminder emails to users that haven't logged in

app/mailers/reminder_mailer.rb, app/models/group.rb, app/services/never_logged_in_notifier.rb, app/services/team_description_notifier.rb, app/views/reminder_mailer/team_description_missing.html.erb, config/locales/en.yml, config/schedule.rb, db/migrate/20160304155510_add_description_reminder_email_at_to_group.rb, db/structure.sql, spec/mailers/reminder_mailer_spec.rb, spec/services/team_description_notifier_spec.rb
- Send reminder email to team leaders of any teams that do not have a team description. 
- Configure to resend after 30 days of having sent the last reminder. 
- Cronjob runs the job each weekday morning.
=> Notify leaders of teams missing team descriptions

app/form_builders/mark_mandatory_labels.rb, app/views/people/_form.html.haml
Move main email hint text to sit between label and input instead of being below the input.
User reported issue caused by hint text being thought to be related to the alternate email field.
Remove the mandatory '*' character from the main email label as this is not a user editable input.
=> Move main email hint text to avoid confusion

app/helpers/application_helper.rb, app/views/search/_person.html.haml, app/views/shared/_breadcrumb.html.haml, app/views/shared/_breadcrumbs.html.haml, spec/helpers/application_helper_spec.rb
* Use full team name in person search result
* Only show team acronyms for first two levels of breadcrumb
* Use team full name for breadcrumb links past the first two levels of the breadcrumb
=> Use full team name in person search result and in breadcrumbs

.dockerignore, Dockerfile, Gemfile
* Reduce number of images created when building application by reducing the number of RUN commands.
* Add .dockerignore file to avoid copying unnecessary files to docker containers.
* Do asset precompile before copying other application files to docker container.
=> Reduce docker build time to speed up builds

.rubocop.yml
=> Exclude gemfile from a rubocop style rule

app/services/group_search.rb, spec/services/group_search_spec.rb
Teams higher in the hierarchy appear further up the results list.
Order exact name team matches by hierarchy ancestry depth.
Order partial team name matches by hierarchy ancestry depth.
=> Order teams by hierarchy in search results

app/services/person_search.rb, spec/services/person_search_spec.rb
Avoid exceptions when searching by removing all punctuation except apostrophes from search term before using it in queries.
Leave in apostrophe so that names containing apostrophes can be searched, e.g. O'Leary.
=> Strip all punctuation except apostrophes from search term

app/helpers/people_helper.rb, app/mailers/reminder_mailer.rb, app/models/group.rb, app/models/person.rb, app/services/never_logged_in_notifier.rb, app/services/person_update_notifier.rb, app/services/team_description_notifier.rb, app/views/reminder_mailer/person_profile_update.html.haml, config/locales/en.yml, config/schedule.rb, spec/mailers/reminder_mailer_spec.rb, spec/models/concerns/acquisition_spec.rb, spec/models/person_spec.rb, spec/services/never_logged_in_notifier_spec.rb, spec/services/person_update_notifier_spec.rb
- Add to cron schedule to trigger sending updates on weekdays.
- Render profile details in reminder email copy.
- Put token login link in reminder email.
- Set the person's `last_reminder_email_at` field when email is sent.
- Throttle emails to 25 per instance per day. So 2 instances will send 50 emails a day.
=> Send profile update email six months after last update

app/assets/javascripts/peoplefinder/team_selector.js, app/views/people/_form.html.haml, app/views/people/_membership_fields.html.haml, app/views/people/add_membership.html.haml, spec/javascripts/peoplefinder/team_selector_spec.js, spec/models/concerns/activation_spec.rb
When user has a membership team set to Ministry of Justice, then show custom team lead question text in order to mitigate the user selecting that they are a leader of that team when they are not.
=>  Show custom team lead question when Ministry of Justice selected

app/services/never_logged_in_notifier.rb, app/services/person_update_notifier.rb, app/services/team_description_notifier.rb, spec/services/person_update_notifier_spec.rb
- Only send profile update emails if last update > 6 months ago.
- Fix limit being ignored in reminder email db queries.
=> Only send profile update emails if last update > 6 months ago

app/views/people/_membership_fields.html.haml
Pass controller set `person` variable to helper method to ensure correct hint text context is shown for team leader and team update fields.
=> Ensure correct hint text shown on new role partials

app/assets/javascripts/peoplefinder/team_selector.js, spec/features/person_membership_spec.rb
When user clicks 'Add another role' ensure custom team lead question text is set based on default team in selector.
=> Show custom team lead question when 'Add another role' clicked

app/models/group.rb, app/models/person.rb, spec/features/group_maintenance_spec.rb, spec/models/group_spec.rb
Remove a team's leaders from the list of people outside of subteams.
Plus, try to fix intermittent failure in group parent editing spec - but it seems that isn't the complete fix.
=> Remove team leaders from people outside of subteams list

app/models/person.rb, app/services/never_logged_in_notifier.rb, app/services/person_update_notifier.rb, spec/models/person_spec.rb, spec/services/never_logged_in_notifier_spec.rb, spec/services/person_update_notifier_spec.rb
Change initial query to find people to send reminders:
- Remove `limit` from initial query
- Use additional scopes to check additional criteria in initial query
Only return people that are eligible for a reminder email from the initial queries. This reduces the size of the number of people returned by these queries.
=> Change query to find people to send reminder email to

app/services/person_search.rb, spec/services/person_search_spec.rb
- Do phrase search and fix name field search
- Change search from `fuzzy_like_this` to `multi_match`
- Put single word query first name matches at top of results
- Reduce number of matches when doing `multi_match` fuzziness search
=> Do exact phrase search and update name and fuzzy searches

app/services/person_search.rb, spec/services/person_search_spec.rb
Remove separate name field search as experimenting showed it apparently reduces the quality of results.
The other searches for exact phase, and for the query term seem to produce adequate results without the name field search.
=> Remove separate name field search to improve results

Gemfile, Gemfile.lock, app/services/person_search.rb, spec/services/person_search_spec.rb
When there is at least one result with a name that is a close Levenshtein edit distance from the query term, then sort the partial results by edit distance in order to get closer edit matches at the top of the results.
=> Sort partial results by name Levenshtein distance from query

app/assets/stylesheets/peoplefinder/people.css.scss, app/controllers/search_controller.rb, app/services/person_search.rb, app/views/search/index.html.haml, spec/services/person_search_spec.rb
To help users identify when there are no exact matches, show a message below the results heading when no exact person name matches have been found.
=> No exact results indicator

app/views/groups/_detail.html.haml, app/views/groups/organogram.html.haml, app/views/layouts/email.html.erb, app/views/reminder_mailer/person_profile_update.html.haml, spec/features/group_browsing_spec.rb
- Change copy on link to organogram
- Remove do not click any links text from email layout
- Replace reply instructions on email
- Correct pluralization of Team leader(s) heading
- Change organogram header text
=> Miscellaneous copy changes

spec/services/person_search_spec.rb
Two results had same edit distance. When sorting by edit distance the order was not guaranteed. Changed spec to reflect this.
=> Fix intermittent person search spec fail

app/controllers/groups_controller.rb, app/controllers/people_controller.rb, app/helpers/application_helper.rb, app/presenters/audit_version_presenter.rb, app/views/shared/_audit.html.haml, spec/features/group_audit_spec.rb, spec/features/person_audit_spec.rb, spec/helpers/application_helper_spec.rb, spec/presenters/audit_version_presenter_spec.rb
Change from showing object `updated_at` time to last audit version `created_at` time for "Last updated" display.
We set last reminder email time on the object, which changes the object `updated_at` time, even though there is no user edit. So it is no longer correct to show object `updated_at` time for the "Last updated" display.
Also format changes to audit log table
- Make field names bold in changes column
- Remove event type
- Format time of event
- Place time in first column
- Show '(deleted)' when new value is blank
=> Fix "Last updated" time to be the last audit version time

app/controllers/people_controller.rb, spec/controllers/people_controller_spec.rb
When a person's profile is deleted, and that person is a member of one or more teams, return browser to the first team page.
=> Return to person's team page when person profile deleted

app/jobs/update_group_members_completion_score_job.rb, app/models/group.rb, app/models/membership.rb, app/models/person.rb, app/views/groups/_subgroup.html.haml, config/initializers/delayed_job.rb, db/migrate/20160418124145_add_members_completion_score_to_groups.rb, db/migrate/20160419131143_populate_group_members_completion_score.rb, db/structure.sql, spec/features/group_browsing_spec.rb, spec/jobs/update_group_members_completion_score_job_spec.rb, spec/models/concerns/completion_spec.rb, spec/models/group_spec.rb, spec/models/person_spec.rb, spec/services/login_spec.rb
The current approach of storing the group's members completion score in the Rails cache with an expiry, was causing delays in page load time when the score cache had expired and needed recalculating.
Instead now store the completeness score in the database. And use a worker job to do any updates to the value.
=> Use job to update group's members completion score and store in database

app/jobs/update_group_members_completion_score_job.rb, spec/jobs/update_group_members_completion_score_job_spec.rb
When a group's members completion score is being updated in the worker job, create a new job to update that group's parent group unless the parent group is the root department group.
We don't display the root department group's members completion score so don't need to update it.
=> Update group's parent members completion score in worker job

.rubocop.yml, Gemfile, Gemfile.lock, README.md, app/models/concerns/hierarchical.rb, app/services/random_generator.rb, db/structure.sql, lib/tasks/peoplefinder/data.rake, lib/tasks/peoplefinder/db.rake, spec/rails_helper.rb, spec/services/random_generator_spec.rb
for use in QA on dev enviroment it is useful
to have some demo data to play around with.
NOTE: set row security to off. This is added by pg_dump
when a migration is run at any point: see
https://www.postgresql.org/docs/current/static/runtime-config-client.html#GUC-ROW-SECURITY
=> add demo data re/loading task

app/assets/stylesheets/peoplefinder/application.scss, app/helpers/upload_helper.rb, app/views/admin/person_uploads/_form.html.haml, app/views/admin/person_uploads/_hint.html.haml, config/locales/en.yml, spec/helpers/upload_helper_spec.rb
The help text html was in a translator but was becoming
too verbose. additionally partialised so as to use helpers.
=> separate and style csv uploader hint into partial

app/services/group_search.rb
search on a single character was raising a 500
error via the Group search code.
=> fix single character search bug

app/services/person_csv_importer.rb, spec/services/person_csv_importer_spec.rb
There is a 14 second unicorn config timeout on the server
which if hit will result in a partial upload success. This
will set a modifiable limit to prevent this situation arising
but is a precursor to increasing the timeout and eventually
running data creation aspect as an asynchronous job.
=> apply an upper limit to number of csv records

.rubocop.yml, Gemfile, Gemfile.lock, app/controllers/admin/person_uploads_controller.rb, app/jobs/person_import_job.rb, app/services/person_creator.rb, app/services/person_csv_importer.rb, config/application.rb, config/environments/test.rb, config/initializers/delayed_job.rb, spec/features/csv_upload_spec.rb, spec/jobs/person_import_job_spec.rb, spec/services/person_creator_spec.rb, spec/services/person_csv_importer_spec.rb, spec/spec_helper.rb
Import people using an asynchronous/background job. This is required because anymore than ~200 records per CSV file will cause a server timeout on any of the environments - see RACK_TIMEOUT and WEB_TIMEOUT env vars
=> Change import to delayed job

app/jobs/person_import_job.rb, app/services/person_creator.rb, spec/jobs/person_import_job_spec.rb
If job fails part way through we do not want subsequent attempts
to create people already created as this hides the original error.
This problem can also be encountered by multiple work instances
executing the job simultaneously.
=> ensure person import job checks existing people

README.md, app/services/token_sender.rb, config/locales/en.yml, spec/features/token_authentication_spec.rb
The request a link method of logging in was deliberatley
not displaying non-permitted domain errors. This is
pointless since the list of domains is available from
the code repo.
=> display error message for non-permitted domains

app/assets/javascripts/peoplefinder/application.js, spec/javascripts/peoplefinder/team_selector_spec.js
hitting 'Enter' (carriage return) in input text fields
defaults to submission of form. This can lead to premature
submission of group and person forms and negatively impact
user experience.
Note that text areas and buttons should still respond to
carriage returns for accessibility and functionality purposes
=> prevent form submission on carriage return in text inout fields (only)

app/assets/javascripts/peoplefinder/application.js
search form field Enter key press 
- default behaviour was deactivated by generic
deactivating of carriage return in previous
commit.
=> ensure search form field carriage return submits

app/controllers/people_controller.rb, app/services/random_generator.rb, app/views/people/_form.html.haml, app/views/people/_profile.html.haml, app/views/people/confirm.html.haml, app/views/reminder_mailer/person_profile_update.html.haml, db/migrate/20160719084601_add_pager_number_to_people.rb, db/structure.sql, spec/models/person_spec.rb, spec/support/profile.rb
For onboarding of NOMS generally and HMPS specifically it is useful to have a pager number field
as this is a common form of communication for the users.
=> Add pager number

app/models/suggestion.rb, app/views/suggestions/new.html.haml, spec/models/suggestion_spec.rb
allow users to suggestion pager number corrections. with a predicated increased uptake of users requiring pager numbers this is likely to be useful.
=> add pager number to incorrect suggestion mailer

db/seeds/data/permitted_domains.yml
As part of 365 rollout a new email address domain is to be used
and will therefore need access to peoplefinder.
=> add new 365 rollout domain access

app/assets/javascripts/peoplefinder/photo_upload.js.erb
Firefox photo cropping was displaying
the image wrongly. This is caused by
firefox requiring a transform and
transform-origin attribute since it
does not respect the obsolete zoom
attribute.
=> fix firefox photo cropping bug

app/services/group_search.rb, spec/services/group_search_spec.rb
The team/group search was returning exact team name matches
as "similar" results based on case alone.
e.g. ministry of magic was only considered similar to Ministry of Magic
=> render group search case-insensitive

app/controllers/search_controller.rb, spec/controllers/search_controller_spec.rb, spec/features/search_spec.rb
This var had been removed in a previous refactor and meant the search results did not show
the original query
=> re-adds the @query variable as required by views

Dockerfile
previous dockerfile was copying only specific asset
files to app prior to precompile but this
meant changes to precompile file locations
(e.g. addition of initializers/assets.rb) were not
being picked up if dockerfile was not amended inline
with those changes.
=> copy entire app prior to assets:precompile

.rubocop_todo.yml, app/jobs/person_import_job.rb, app/jobs/update_group_members_completion_score_job.rb, app/models/person.rb, spec/jobs/person_import_job_spec.rb, spec/models/person_spec.rb
bulk uploading was enqeuening thousands of low priority
updates of groupmembershipscompletion scores. It just needs
running once for the group specified by the bulk upload.
=> prevent unnecessary Group completion score updates from bulk upload

app/jobs/update_group_members_completion_score_job.rb, spec/jobs/update_group_members_completion_score_job_spec.rb
sentry errors raised as a result of a group being deleted
before background jobs to update the groups score were run,
by which time of course the group did not exist.
=> reduce the number of times the Job in question is attempted

Gemfile, Gemfile.lock, app/assets/stylesheets/peoplefinder/people.css.scss, app/controllers/groups_controller.rb, app/models/group.rb, app/models/person.rb, app/views/groups/_all_people_pagination.html.haml, app/views/groups/all_people.html.haml, config/locales/en.yml, spec/controllers/groups_controller_spec.rb, spec/models/group_spec.rb, spec/models/person_spec.rb
the all_people view was encountering a preamture termination from the upstream unicorn server. This is almost certainly caused by 18000 profiles in a particular parent team (noms). 
This PR adds pagination to the view to prevent this issue.
=> Add pagination to all people view

app/services/group_search.rb, spec/services/group_search_spec.rb
entering * in search was raising a 500. Any non-word
character entered as search term would cause this
error.
=> prevent single non-word characters raising 500 errors

app/models/concerns/bucketed_completion.rb, app/models/concerns/completion.rb, app/models/person.rb, app/services/metrics_publisher.rb, app/services/person_update_notifier.rb, config/database.yml, spec/models/concerns/bucketed_completion_spec.rb, spec/models/concerns/completion_spec.rb, spec/services/metrics_publisher_spec.rb
Previous method of calculating average completion score was timing out when polled by Geckboard. Almost certainly resulting from addition of 20K odd additional users and a join to group table that was being performed by ruby per person. 
This PR changes the calculation to be performed entirely on the database and is several hundred orders of magnitude faster.
=> Scalable completion score metrics

app/models/concerns/acquisition.rb, app/models/concerns/activation.rb, app/models/concerns/completion.rb, spec/models/concerns/activation_spec.rb, spec/models/concerns/completion_spec.rb
Stops acquisition and activation metrics raising 5xx errors. This is almost certainly a result of the non-scalable combination of AR sql and ruby looping. Tested locally using:
```
puts Benchmark.measure { Person.activated_percentage(from: Date.today-365 }
```
=> amend activation metrics to ensure they are scalable

app/models/token.rb, spec/models/token_spec.rb, spec/support/matchers/delayed_job_matchers.rb
required for scalability since mailer jobs
can create large numbers of tokens that will expire at
the same time. This can caused 500 errors on hitting the request link
button in the login page (i.e. when
the destruction of expired tokens is performed
synchronously, initiated by a token request event.
=> Asynchronous expired token destruction

app/assets/stylesheets/peoplefinder/peoplefinder-ie7.css.scss, app/views/layouts/home.html.haml
In IE7 the team and group images were displaying
as block (vertical) rather than inline (horizontal).
=> add IE7 organogram fix

app/models/group.rb, spec/models/group_spec.rb
previously this was using a combination of ruby inject and sql which is slow for large groups of people. changed to use existing sql based solution for scalability.
=> Improve group score update speed

app/models/concerns/geckoboard_datasets.rb, lib/geckoboard_publisher/profiles_changed_report.rb, spec/lib/geckoboard_publisher/profiles_changed_report_spec.rb, spec/support/shared_examples_for_geckoboard_reports.rb
Geckboard datasets are limited to 500 records and this report regularly exceeds it.
=> apply profiles changed report limitation of 500 records

app/models/concerns/geckoboard_datasets.rb, lib/geckoboard_publisher/profiles_percentage_report.rb, spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb
To assist in determining team accuracy this metric returns profiles in teams that have sub teams i.e. not at the tip of a branch in the directory structure. Ideally there should be relatively few people in such teams.
=> add metrics for number of people in a team not at a branch tip

config/schedule.rb
This is to avoid clashes with late night workers but
particularly bulk upload schedules.
=> change stat pushing schedule to be in the morning

config/schedule.rb, spec/support/matchers/whenever_matchers.rb
This avoids conflict errors that can arise when you change the
dataset schema/fields for an existing/published dataset.
=> force dataset replacement

lib/geckoboard_publisher/profile_completions_report.rb, spec/lib/geckoboard_publisher/photo_profiles_report_spec.rb, spec/lib/geckoboard_publisher/profile_completions_report_spec.rb, spec/lib/geckoboard_publisher/profiles_changed_report_spec.rb, spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb, spec/lib/geckoboard_publisher/total_profiles_report_spec.rb
change the profile completion geckoboard dataset to use percentage of total profiles for those with photos and additional info. Makes it easier to compare teams completion stats - rather than the previous raw counts.
Also, apply more robust field set tests to all geckoboard dataset specs - to include Field type/class test.
=> Geckoboard team profile percentages

app/models/concerns/geckoboard_datasets.rb, lib/geckoboard_publisher/profile_completions_report.rb, lib/geckoboard_publisher/profile_duplicates_report.rb, lib/geckoboard_publisher/profiles_changed_report.rb, lib/geckoboard_publisher/report.rb, spec/lib/geckoboard_publisher/profile_completions_report_spec.rb, spec/lib/geckoboard_publisher/profile_duplicates_report_spec.rb, spec/lib/geckoboard_publisher/profiles_changed_report_spec.rb, spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb, spec/lib/geckoboard_publisher/total_profiles_report_spec.rb, spec/support/matchers/general_matchers.rb, spec/support/shared_examples_for_geckoboard_reports.rb
Adds a report on duplicate people. 
Also modifies the super class for geckboard publisher to chunk POST/PUTs, to the API at 500 records each - to match the APIs limits.
NOTE: am thinking to refactor some of the SQL to Query objects and use arel
=> Geckoboard duplicate profiles

spec/controllers/concerns/shared_examples_for_session_person_creator.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/tokens_controller_spec.rb
fixes:
```
WARNING: Shared example group 'session_person_creatable' has been previously defined at:
/Users/jsugarman/rails_projects/ds_work/peoplefinder/spec/controllers/concerns/session_person_creator_spec.rb:3
...and you are now defining it at:
/Users/jsugarman/rails_projects/ds_work/peoplefinder/spec/controllers/concerns/session_person_creator_spec.rb:3
The new definition will overwrite the original one.
```
...that occured on running rspec.
=> fix warning on use of shared examples

app/views/people/confirm.html.haml, spec/features/person_membership_spec.rb, spec/support/profile.rb
when creating/editing a profile the flow checks whether
the person is a duplicate, however the leader and subscription
attributes were not being stored in the hidden fields on the
confirmation page thereby causing them to be lost on subsequent
submission.
=> fix bug stopping saving of leader/subscription change

app/models/group.rb, app/models/person.rb
Team pages query the number of people that are in that team but not in a subteam thereof. For MoJ and NOMS teams the query method was taking 14+ secs and resulting in a timeout for the response and consequently raising a 500 error to the user.
This PR creates a more efficient scope which hits the db only once for the count
=> fix scalability of people in subteams count query

.env, app/models/ip_address_matcher.rb, app/models/readonly_user.rb, config/application.rb, config/environments/test.rb, spec/features/group_maintenance_spec.rb, spec/features/home_spec.rb, spec/features/login_page_spec.rb, spec/features/person_maintenance_spec.rb, spec/features/suggestion_spec.rb, spec/models/ip_address_matcher_spec.rb, spec/models/readonly_user_spec.rb, spec/support/login.rb
The IP whitelist needs to be handled in the deploy
repo as an environment variable rather than nginx
header insertions. The app then needs to handle this
this via config and code based on a requests remote
ip.
=> amend read-only user ip whitelist mechanism

Dockerfile, Gemfile, Gemfile.lock, circle.yml
Tried 2.4.0 (rc1) but this is incompatible with json 1.8.3
that is required by rails 4.2.7. rails 4.2.8 is intended to
fix this but is not yet available. could also use latest json 1.8 branch
explicitly in Gemfile but requires rails branch usage. Will await
ruby version bump or rails version bump.
see:
- [Stack Overflow](http://stackoverflow.com/questions/41298904/is-it-possible-to-run-a-rails-4-2-app-on-ruby-2-4)
- [Github Issue](https://github.com/flori/json/issues/303)
=> update ruby to 2.3.3

app/services/person_creator.rb, spec/features/group_browsing_spec.rb, spec/services/person_creator_spec.rb
New profiles created via the GUI need not be given a membership of a team. This results in profiles that are not locatable through navigation of the team structure - they are are findable via search. This PR defaults new profiles created without a membership to be in the Top level team - MoJ.
=> default team membership to MoJ if none specified

app/controllers/problem_reports_controller.rb, app/models/permitted_domain.rb, spec/features/report_a_problem_spec.rb
Attempting to login with a google address that isn't in permitted domains will
lead to a CSRF error when redirecting back to the original page.  This PR allows
us to detect that, and redirect to the login page.
=> Prevent CSRFs and 404s after reporting a problem

app/assets/stylesheets/peoplefinder/application.scss, app/assets/stylesheets/peoplefinder/peoplefinder-ie7.css.scss, app/assets/stylesheets/peoplefinder/peoplefinder-lt-ie9.css.scss, app/helpers/application_helper.rb, app/views/groups/_form.html.haml, app/views/layouts/application.html.haml, app/views/people/_form.html.haml, app/views/sessions/person_confirm.html.haml, app/views/shared/_building_alert.html.haml, app/views/shared/_editing_alert.html.haml, config/locales/en.yml, spec/features/group_maintenance_spec.rb, spec/features/person_maintenance_spec.rb
remove editing and building alerts/flash notices. These user messages are redundant given the context of the pages they display on and the designer requested their removal.
=> remove editing and building alerts

spec/lib/geckoboard_publisher/photo_profiles_report_spec.rb, spec/lib/geckoboard_publisher/profile_completions_report_spec.rb, spec/lib/geckoboard_publisher/profile_duplicates_report_spec.rb, spec/lib/geckoboard_publisher/profiles_changed_report_spec.rb, spec/lib/geckoboard_publisher/profiles_percentage_report_spec.rb, spec/lib/geckoboard_publisher/total_profiles_report_spec.rb, spec/spec_helper.rb
previous rpsec config was unnecessarily stubbing geckboard api for all tests. This ensures the GB api calls are only stubbed for relevant/tagged tests
=> stub geckoboard requests for geckoboard specs only

app/services/person_search.rb, spec/services/person_search_spec.rb
This is a small change to the person search class that ensures that exact name matches are case-insensitive. These matches are forcibly placed at the top, regardless of synonym equivalence.
The prior case-sensitivity may have been an oversight  - especially since the any_exact_matches? method applies case-insenstive logic
=> change person search results for exact names to be case-insensitive

app/controllers/concerns/session_person_creator.rb, app/controllers/people_controller.rb, app/controllers/profile_photos_controller.rb, app/helpers/state_cookie_helper.rb, app/jobs/person_import_job.rb, app/services/person_creator.rb, app/services/person_updater.rb, app/services/state_manager_cookie.rb, app/views/people/_form.html.haml, app/views/people/confirm.html.haml, app/views/person_image/edit.html.haml, spec/controllers/people_controller_spec.rb, spec/features/group_maintenance_spec.rb, spec/jobs/person_import_job_spec.rb, spec/services/person_creator_spec.rb, spec/services/person_updater_spec.rb, spec/services/state_manager_cookie_spec.rb
The creation and editing page is now split into three actions - intial create,
editing the photo, editing other information, but this appears to the user as
one editing session. Before this PR, we were getting confusing flash messages
at each stage, as well as an email generated at each stage.
This is now controlled by a cookie (abstracted into s StateManagerCookie object)
which records whether or not the session started with a create or an update, and
whether this action is the result of the final save button being pressed.  This enables
use to send the correct email and display the correct flash message only upon
completions
=> StateManagerCookie

app/services/person_search.rb, app/views/search/_person.html.haml, app/views/search/_person_confirmation.html.haml
1. show role for search results that have no hit on role and group.
2. prevent duplicate role and group links
=> fix bug on search result display for role and group

app/services/search_results.rb, spec/features/search_spec.rb
null string returns a search result of empty array rather than Elasticsearch records object. This PR fixes the issue by providing an override enumerable method to handle the possible types returned
=> fix null search 500 error

app/assets/stylesheets/peoplefinder/admin.scss, app/controllers/admin/management_controller.rb, app/jobs/generate_report_job.rb, app/policies/admin/management_policy.rb, app/views/admin/management/show.html.haml, config/initializers/delayed_job.rb, config/locales/en.yml, config/routes.rb, config/schedule.rb, lib/csv_publisher/user_behavior_report.rb, spec/config/schedule_spec.rb, spec/jobs/generate_report_job_spec.rb, spec/lib/csv_publisher/user_behavior_report_spec.rb, spec/policies/admin/management_policy_spec.rb
User behaviour report takes over 14 seconds to run on production. This hits the server timeout and therefore a background job is necessary to run it.  
This PR adds a generate link to enable users to kick of the background job to get the latest data and  adds a nightly scheduled job as well.
=> add background job for generating user behaviour report

app/jobs/update_group_members_completion_score_job.rb, spec/jobs/update_group_members_completion_score_job_spec.rb, spec/models/concerns/completion_spec.rb, spec/models/person_spec.rb
Completion score update jobs are being enqueued for the same group
multiple times. You only need one enqueued job per group at
any one moment in time.
=> prevent enqueuing of unnecessary completion score update jobs

config/schedule.rb, spec/config/schedule_spec.rb
required for testing. Mail interceptor redirects mail to support
inbox in any event. This was as intended before the single email
notification mailer went in too.
ticket PFT-285
=> add queued notification processing to demo (and dev)

.rubocop_todo.yml, app/jobs/update_group_members_completion_score_job.rb, app/presenters/membership_change_set.rb, app/presenters/membership_changes_presenter.rb
An activerecor:recordnotfound error can be raise if a team
is removed between enqueuing of an email job and its processing.
=> prevent record not found error when processing user update email

app/views/people/_form.html.haml, spec/features/person_maintenance_spec.rb
remove preview button as prelude to removing all functionality and historical data.
see [ticket PFT-273](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=49&projectKey=PFT&view=detail&selectedIssue=PFT-273)
=> hide preview button

app/helpers/elasticsearch_helper.rb, app/services/person_search.rb, app/views/search/_person.html.haml, spec/features/search_spec.rb
elastic search highlighting requires an html_safe
on the es rendered html. This meant that js script
tags could be rendered unescaped.
=> remove xss attack vector

app/views/search/index.html.haml
puts people before groups in the search results, as requested by PM.
=> change the order of search results

app/assets/stylesheets/modules/_module-suggestions.scss, app/form_builders/suggestion_form_builder.rb, app/views/suggestions/create.html.haml, app/views/suggestions/new.html.haml, config/locales/en.yml, spec/features/suggestion_spec.rb, spec/form_builders/form_groups_spec.rb, spec/form_builders/suggestion_form_builder_spec.rb
Applies the govuk elements styling to the suggestions form elements via a domain specific form builder. 
GovukElementFormBuilder does not cater for individual checkboxes (checkbox fieldsets only) so this wraps the logic of an individual check box to output the expected html for a govuk styled checkbox (and allow for pass thru of other options).
=> apply govuk styling to suggestion form elements

spec/rails_helper.rb
The govuk_frontend_toolkit-5.2.0 has a deprecation warning
in selection-button.js that cannot be turned off.
Once this is resolved in the gem or in the app then we can revert
to using standard poltergiest driver. If you want to enble logging
for dev work just uncomment the `Capybara.javascript_driver = :poltergeist`
line in `rails_helper.rb`.
=> register javascript driver to redirect console logging to /dev/null

app/views/search/_person.html.haml
if a JS script is injected into a role then
a search that highlights the role and team
would execute it.
=> close xss attack vector on role field

app/models/membership.rb, app/validators/permanent_secretary_unique_validator.rb, config/locales/en.yml, spec/factories.rb, spec/models/membership_spec.rb
On regular occasions users have inadvertently made themselves
the leader of the top-level "Department" (Ministry of Justice).
This validation prevents this unless the current perm.sec.
is either deleted, moved to another team or modified to
not be the leader.
=> validate uniqueness of the Permanent Secretary

Gemfile.lock
A security alert was raised by gemnasium:
Sources: https://github.com/sparklemotion/nokogiri/issues/1634
http://people.canonical.com/~ubuntu-security/cve/2017/CVE-2017-5029.html
http://people.canonical.com/~ubuntu-security/cve/2016/CVE-2016-4738.html
=> bump nokogiri 1.7.1 --> 1.7.2

app/helpers/search_helper.rb, app/views/search/_filter_sidebar.html.haml, config/locales/en.yml, spec/features/search_filter_spec.rb, spec/features/search_spec.rb, spec/helpers/search_helper_spec.rb
Following design advice it was recommended
to remove much of the content from the filter sidebar
and simplify the result summary.
=> Change content of filter sidebar and result summary

app/assets/stylesheets/application.scss, app/assets/stylesheets/modules/_module-team-selector.scss, app/helpers/org_browser_helper.rb, app/views/shared/_org_browser_level_heading.html.haml, spec/features/group_maintenance_spec.rb, spec/features/person_membership_spec.rb
Hide the radio button on the MOJ level to stop a person from selecting it
=> Team selector MOJ level fixes

.rubocop_todo.yml, app/assets/stylesheets/modules/_module-team-selector.scss, app/helpers/org_browser_helper.rb, app/models/concerns/data_migration_utils.rb, app/models/person.rb, app/views/people/_membership_fields.html.haml, app/views/shared/_org_browser_level_heading.html.haml, lib/tasks/peoplefinder/data.rake, spec/models/person_spec.rb
There are many profiles on prod that are not
associated with any team. These are to be moved
to the department level.
=> add task to move non-team-members to department

app/views/people/_team_selector.html.haml
The ability to create new subteam via the team selector
was only enabled on the edit profile flow. This has
now been enabled for new profiles too, to encourage
accurate team memberships creation.
=> enable team creation via new profile form

app/form_builders/person_form_builder.rb, app/validators/permanent_secretary_unique_validator.rb, app/views/people/_membership_fields.html.haml, app/views/people/_team_selector.html.haml, config/locales/en.yml, lib/ext/govuk_elements_errors_helper_extensions.rb, spec/features/person_maintenance_spec.rb, spec/models/membership_spec.rb, spec/support/pages/sections/error_summary.rb, spec/support/pages/sections/profile_form.rb
**Why?**
current message for when a user attempts to make themselves leader of the MoJ is unclear.
**What?**
Change the error message based on feedback and add field level error and link to it
=> alter perm.sec. unique validation error message

app/mailers/problem_report_mailer.rb, spec/mailers/problem_report_mailer_spec.rb, spec/models/problem_report_spec.rb
PM has set up an auto response for the support inbox. In
order for problem report form submitters to receive this the
reply-to needs to be set on the email that is sent to the support email
by the form. It is set to the reporters email address, if available.
=> set reply-to header for problem report submission

app/models/concerns/data_migration_utils.rb, lib/tasks/peoplefinder/data.rake, spec/models/person_spec.rb
Exclude people in MoJ that have a role. This is because some people
may have a job title/role in MoJ that is deliberately different from
their role in another team.
=> modify the department_members_in_other_teams scope

app/helpers/mail_helper.rb, app/mailers/token_mailer.rb, app/views/layouts/email.text.erb, app/views/token_mailer/new_token_email.text.erb, spec/mailers/token_mailer_spec.rb
**what**
send text only token login emails to OMNI probation addresses 
**why**
probation users on OMNI network use lotus notes 7 as email client. This client
does not respect HTML (see [lotus notes overview](https://litmus.com/community/learning/20-lotus-notes-overview) and [email client css compatability table](https://i3.campaignmonitor.com/assets/files/css/campaign-monitor-guide-to-css-in-email-sep-2013V2.pdf?ver=2157&_ga=1.39670883.1992293110.1386961694)).
Lotus Notes makes copying and pasting the token into Firefox (rather than using their default IE6 browser) very difficult and the lack of html tag support means we cannot ease it.
Once probation are migrated they will have justice.gov.uk addresses that will receive the standard multipart email in any event and this work could be …
=> render text emails only for probation token login

app/models/concerns/data_migration_utils.rb, lib/tasks/peoplefinder/data.rake, spec/models/person_spec.rb
**What**
remove redundant team memberships.
**Why**
There are some profiles that have a department level
membership and a sub-team membership and the department level
membership has no role. The membership therefore serves no purpose 
and is a blocker to possible validations.
=> add scope/query for unnecessary department level memberships

spec/mailers/previews/preview_helper.rb
Mailer previews relying on creation of the instigator
were failing due to team membership validation failures.
=> Fix mailer previews

app/models/token.rb, spec/features/token_authentication_spec.rb, spec/models/token_spec.rb
requested by PM in an attempt to cut down
on support requests related to expired
tokens, particularly for individuals using
shared mailboxes.
=> Increase token throttle limit to 24 hours

app/views/sessions/_login_page.html.haml, app/views/tokens/create.html.haml, config/locales/en.yml, spec/features/login_page_spec.rb, spec/features/token_authentication_spec.rb
**What**
Change token sent page content to reflect new token expiry limit
**Why**
The TTL was changed but the time limit warning content was hardcoded
with no tests. This PR makes it dynamic and adds a test.
=> amend token time limit warning

app/assets/javascripts/peoplefinder/photo_upload.js.erb
Why are we doing this:
Users have reported issues in IE11 with the photo uploader.
In IE11 any error message returned by the server is not visible.
In ie11, when a file input is cleared, it will also fire the change event. This caused the error message to be hidden right after it was shown
@jsugarman  smashed it and found what the issue was
See:
https://github.com/facebook/react/issues/8793
=> Photo upload error message fix

config/kubernetes/production/deployment.yaml
Following a short outage on the People Finder production application, we noticed that there were only 2 pods in the deployment. Fixing here. 
https://mojdt.slack.com/archives/CC3A275NU/p1584983259012200
=> Increase required pods from 2 to 4 in production

config/initializers/action_view_patch.rb
"There is a possible XSS vulnerability in ActionView's JavaScript literal escape helpers. Views that use the j or escape_javascript methods may be susceptible to XSS attacks.
For those that can't upgrade, the following monkey patch may be used
See GHSA-65cv-r6x7-79hv"
=> Monkey patch escape JavaScript method to prevent XSS vulnerability

config/kubernetes/demo/deployment.yaml, config/kubernetes/demo/ingress.yaml, config/kubernetes/development/deployment.yaml, config/kubernetes/development/ingress.yaml, config/kubernetes/production/deployment.yaml, config/kubernetes/production/ingress.yaml, config/kubernetes/staging/deployment.yaml, config/kubernetes/staging/ingress.yaml
Prepare for Kubernetes upgrade to 1.16
https://dsdmoj.atlassian.net/browse/CT-2940 (task)
https://dsdmoj.atlassian.net/browse/CT-2890 (ticket)
Need to apply Ingress and Deployment files at the very least. Might be best to full deploy anyway.
First deploy dev / staging etc, and see if it works. Then prod. And then...
Check if the application still works on all namespaces after CP upgrade the week commencing API on 12th July.
=> CT-2940 Remove deprecated k8s apis june 2020

config/kubernetes/demo/deployment.yaml, config/kubernetes/staging/deployment.yaml
For demo, dev and staging we only need 1 Kubernetes webserver pod, as it's non-critical env -
=> Reduce replicas down to 1 for non-prod environments

db/seeds/data/permitted_domains.yml
Add “@publicguardian.gov.uk” to the existing approved list of email domains.
OPG staff now have gov.uk email addresses (not gsi) but the people finder will not allow the email addresses to be updated. 
Deployment: run `rake db:seed` on the namespace to update the list of permitted domains
Testing - verify this task is non-destructive and makes no other changes
=> CT-3087 Add publicguardian.gov.uk to permitted domains

app/assets/javascripts/peoplefinder/photo_upload.js.erb
Fixes bug whereby uploaded profile photos were not able to save after upload/cropping as the save button appears as disabled.
The issue is that the button was disabled (greyed out) as in this screen cap:
**To test:**
- run the app locally 
- find a profile
- click `edit this profile` > `change this photo` > `choose file`
- upload the profile pic you want
- crop the photo and click `crop photo`
- click save (**Note this should no longer be greyed out**)
- the profile photo should now reflect your uploaded photo.
=> Enable save button on profile picture upload

config/kubernetes/demo/deployment.yaml, config/kubernetes/development/deployment.yaml, config/kubernetes/production/deployment.yaml, config/kubernetes/staging/deployment.yaml, pull_request_template.md
Because we use the same endpoint /healthcheck for both pingdom and our liveness probes, it prevents us from viewing the error message when there is an outage, as it removes all our pods from the service. It looks like this is an antipattern. Poornima suggests we follow the practice of using /ping for the liveness and readiness probes (as CCCD does), and reserve healthcheck for Pingdom.
When outages appear we should be able to get information more directly from the app because the pods will still be reachable by http
ALSO Added PR template :) 
https://dsdmoj.atlassian.net/browse/CT-3206
=> CT-3206 Switch probe endpoints to stop cluster dropping all pods

.circleci/config.yml
Deploy master to demo was being done automatically, we rather want it to deploy to demo on approval with no dependency on dev.
https://dsdmoj.atlassian.net/browse/CT-3138
requires deployment to be tested after merging on circleci
merge this, you should then it should deploy to dev automatically, but demo should be optional, and staging should depend on dev, and production on staging (plus approvals)
=> CT-3138 Fix workflow for Circleci demo

config/kubernetes/production/cronjob-delete-old-ecr-images.yaml
Increase number of left over master images to 25 for safety against losing the one on production (if 10 master images are built, that are not on prod, then the prod one would be deleted).- so reduce risk - make it 25
https://dsdmoj.atlassian.net/browse/CT-3301
n/a
n/a - once on production, we should gradually see master images increase to 25. this can be tested by querying the images using this command: aws ecr list-images --region eu-west-2 --repository-name [repo name]  --query 'imageIds[*]' --output json
=> CT-3301 Increase no of master images to keep

db/seeds/data/permitted_domains.yml
Add criminalappealoffice.justice.gov.uk to allowed domains for peoplefinder
Before
after:
https://dsdmoj.atlassian.net/browse/CT-3319
NOTE: After deploying, login to webapp container:
```
rails c
PermittedDomain.create(domain: 'criminalappealoffice.justice.gov.uk')
```
Try requesting a token for this domain, criminalappealoffice.justice.gov.uk shouldn't get error - then once on production check with the reporter - https://dsdmoj.atlassian.net/browse/CT-3319
=> CT-3319 Add criminalappealoffice.justice.gov.uk to permitted domains

db/seeds/data/permitted_domains.yml
Add ppo.gov.uk domain into permitted domains list
Before:
After: 
https://dsdmoj.atlassian.net/browse/CT-3391
Requires manually adding domain through console for each environment
Try entering ppo.gov.uk email into Email check page on peoplefinder.
=> CT-3391 Add ppo.gov.uk to allowed domains

config/application.rb
Generate user behaviour report in production mode failed with
NameError (uninitialized constant Admin::ManagementController::CsvPublisher):
app/controllers/admin/management_controller.rb:7:in `generate_user_behavior_report'
Rails autoloader is expecting files in lib to have the right naming conventions mapping file name to module and class names. The class gets included when app runs in development mode (i.e. tests pass and app works locally) but not when running in production mode, causing a crash when trying to generate the user behaviour report on K8s environments. Tried eager loading all the classes in /lib as described in some sources, but the eager load path is a frozen variable now; also, this the behaviour that Rails core team [decided to …
=> CT-3424 Autoloading has changed - require module from /lib directory directly

app/models/health_check/database.rb, spec/features/application_health_check_spec.rb, spec/models/health_check/database_spec.rb
We saw consistent "outages" reported by Pingdom following the Rails 5.0->5.2 update; on investigation these seemed to be spurious, and only happened when the site was inactive - overnight or over the weekend. 
This PR changes slightly the ActiveRecord method used to see if the connection is available. 
I think the old method was checking whether ActiveRecord is ephemerally holding an open connection, which gets released if it isn't being used, and so isn't a reliable way to check whether ActiveRecord _can_ connect. The new method seems to act more like it seems to have done in the older version of Rails and is the method used in CTS which doesn't suffer from the same intermittent "failures".  
n/a
https://dsdmoj.atlassian.net/browse/CT-3088
n/a
None. We just want to keep an eye on Pingdom …
=> CT-3088 Amend db check method

config/kubernetes/demo/deployment.yaml, config/kubernetes/development/deployment.yaml, config/kubernetes/production/deployment.yaml, config/kubernetes/staging/deployment.yaml
We use the govspeak gem which has a bunch of gov_uk dependencies, including govuk_publishing_components and a thing  named plek (also gov uk) - this gem requires two env_vars to be set in production, which was causing deployments to fail because they were not set and the rails server was refusing to boot when the container was being launched in kubernetes. 
```iananderson@L0419 ~/dev/moj/peoplefinder CT-3449-fix-govuk-gem $ klog peoplefinder-development webapp
running app server - unicorn
I, [2021-02-24T15:56:25.145391 #6]  INFO -- : Refreshing Gem list
Plek::NoConfigurationError: Expected GOVUK_WEBSITE_ROOT to be set. Perhaps you should run your task through govuk_setenv <appname>?
/usr/local/bundle/gems/plek-4.0.0/lib/plek.rb:166:in `env_var_or_dev_fallback' …
```
=> CT-3449 fix govuk gem

Gemfile, Gemfile.lock
This gem has been merged into the sinatra project so updates are
supplied there rather than in the deprecated repo pointed at by the
regular gemfile declaration.
See: https://github.com/sinatra/rack-protection
[CT-3643](https://dsdmoj.atlassian.net/browse/CT-3643)
=> Pulls rack-protection from the sinatra repo

app/controllers/admin/management_controller.rb, app/jobs/generate_report_job.rb, app/queries/user_behavior_query.rb, config/initializers/delayed_job.rb, spec/jobs/generate_report_job_spec.rb, spec/queries/user_behavior_query_spec.rb
Adds percent_complete column to the User Behaviour report
There were a few errors appearing with this which meant it took a while to solve
firstly, adding this adds a little bit more work to the query generation so  I had to batch the creation of the report with `find_in_batches` to stop using up all the RAM.  This allowed the reports to be generated manually but there were still errors on the various environments as the job to generate in the background was failing.
some errors over how we passed the constant report name to the generator meant that the worker was failing to to generate the report.
This was the case in `main` as well, so I know it was unrelated to my changes.
Its a hard one to debug as the code grabs the last report - so if there is one in the DB it will allow you to …
=> CT-3722 Add percent complete to UB report

app/services/person_update_notifier.rb, spec/services/person_update_notifier_spec.rb
this allows their last_email_remider_at field to be updated
previously this wasn't happening, which meant some people receiving
emails everyday.
[CT-3763](https://dsdmoj.atlassian.net/browse/CT-3763)
n/a
Comment out: https://github.com/ministryofjustice/peoplefinder/blob/ec4aa84a4357f824156ab62f17670218b08673d8/app/services/person_update_notifier.rb#L24 and you should see the new tests fail.
=> CT-3763 Skips some validation if users don't have a team

README.md, app/controllers/application_controller.rb, app/views/sessions/_login_page.html.haml, app/views/shared/_feedback_form.html.haml, config/locales/en.yml, spec/features/report_a_problem_spec.rb, spec/features/search_spec.rb, spec/rails_helper.rb
Due to the spamming that has been received into Google Groups, it has been suggested that we remove the ‘Report a problem’ located in the footer from all the logged out pages.
In addition, so people still have a way to report login issues, the support email address has been added to the sign in / request link page.
The copy/placement can be discussed.
Note: as part of this work, I had some issues setting up ElasticSearch locally and making it work, so I tweaked the README instructions with what, in the end, helped me getting this up and running.
Also, when running the app/tests there were several deprecation warnings that I resolved (Pundit, Selenium...)
https://dsdmoj.atlassian.net/browse/CT-4200
1. When logged out, the "report a problem" doesn't show in the footer.
2. When logged in, …
=> CT-4200 Remove report a problem from logged out pages

README.md
In a recent audit, it was raised as a false alarm the fact the CircleCI badge contains a token.
However this token scope is only "status" and can only be used to retrieve the status of a build (pass/fail).
The token is there because this repo used to be private, and private repos badges can only work with a token.
As the repo is no longer private, and in order to no raise more false alarms in the future, I'm updating the badge to the "public" one, no longer needing a token, and will revoke the token so it cannot be used.
Also, removed the badge for gemnasium because that service is no longer active.
=> Update CircleCI badge and remove Gemnasium

app/assets/stylesheets/modules/_module-pagination.scss
Make display all xx people text go darker to fix contrast issue
Before:
After: 
https://dsdmoj.atlassian.net/browse/CDPT-267
Click on "View all people" under About team
=> CDPT-267 'Displaying all...' text to be darker

Gemfile.lock
webdrivers 5.0.0 has a bug on M1 macs where it uses the wrong naming convention when trying to download chromedriver (https://github.com/titusfortner/webdrivers/issues/237). This is fixed in 5.2.0.
=> Upgrade webdrivers gem

lib/tasks/peoplefinder/db.rake
This table was added in Rails 5. It doesn't exist as an AR class so it needs to be skipped when resetting column information as part of the seeding task.
=> Ignore ar_internal_metadata table

app/mailers/user_update_mailer.rb, spec/mailers/user_update_mailer_spec.rb
Exceptions are being caused in the mailer to notify when a profile has been updated due to the person not existing.
This is likely because a person has been deleted.
This change means it will not attempt to send an email if the person no longer exists.
=> CDPT-391 Handle deleted person in mailer

config/kubernetes/demo/env-configmap.yaml, config/kubernetes/development/env-configmap.yaml, config/kubernetes/production/env-configmap.yaml, config/kubernetes/staging/env-configmap.yaml
Upgrading security of Peoplefinder on Cloud Platform means that the URL for the new pod no longer works when creating index. Therefore we have to remove the HTTP.
https://dsdmoj.atlassian.net/browse/CDPT-475
n/a
=> CDPT-475 Make Elastic search pod host name SSL friendly

.gitignore, README.md
Add command to create elastic search index because even though the env var is udpated the "new" client still reverts to localhost, unless first you set it to the right address.
=> Cdpt 475 update readme around elastic search

spec/features/person_maintenance_spec.rb, spec/spec_helper.rb, spec/support/profile.rb
In a previous PR we accidentally deleted the CSRF token `= csrf_meta_tag` from the application template file which prevented many actions from working but didn't get flagged in our tests. This is because CSRF is disabled in the test environment in Rails 
To cover this scenario I've amended our delete user spec (the specific scenario which alerted us to the issue) to use CSRF tokens (which requires the JS driver) as a sort of canary against this in the future. 
https://dsdmoj.atlassian.net/browse/CDPT-382
N/A
Remove line 22 of application.html.haml and run the spec `spec/features/person_maintenance_spec.rb` and it will throw an exception
=> CDPT-382 check csrf token present

.circleci/config.yml, Gemfile.lock, config/kubernetes/production/cron-never-logged-in-notifier.yaml, config/kubernetes/production/cron-person-notifier.yaml, config/kubernetes/production/cron-person-update-reminder.yaml, config/kubernetes/production/cron-photo-profiles-report.yaml, config/kubernetes/production/cron-profile-changed-report.yaml, config/kubernetes/production/cron-profile-completions-report.yaml, config/kubernetes/production/cron-profile-percentage-report.yaml, config/kubernetes/production/cron-team-description-notifier.yaml, config/kubernetes/production/cron-total-profiles-report.yaml, config/kubernetes/production/cron-user-behaviour-report.yaml
The Cloud Platform Kubernetes cluster is being updated and support is being dropped for the current CronJob API we use.
* [x ] (7) PR Prefixed with ticket number e.g. `CT-7654 ...`
=> CDPT-1148:PF Remove beta1 version from cron jobs

config/kubernetes/production/cron-person-notifier.yaml
Currently the person-notifier cronjob is crash/looping.  Attempting to view logs returns a “/bin/sh: rails: not found” error.
To fix this, the cron-person-notifier.yaml file was updated prefixing 'bundle exec' to runner rails command.
N/A
N/A
N/A
When viewing the pods with kubectl  the person-notifier-xxxxxxxx-xxxxx pod should not be in a 'CrashLoopBackOff' state.
=> Fix person-notifier cronjob crash looping.

.circleci/config.yml, Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/spec_helper.rb
- Stops uploading test coverage details to CodeClimate
- Adds saving of coverage as an artifact in CircleCI
- Fails build if test coverage is under a set percentage (currently 95%)
=> Remove CodeClimate and save coverage report

app/services/health_check_service.rb, spec/services/health_check_service_spec.rb
We regularly are seeing downtime issues according to Pingdom overnight. We have no visibility on the issue, so this change will send details of any health check failures to Sentry.
=> Log health check errors in Sentry

app/mailers/reminder_mailer.rb
There is a regular error occurring on the sending of emails to inform a user their profile has been updated. This happens when the profile has no secondary email or no description.
=> Handle profiles missing some attributes

config/kubernetes/production/ingress-live.yaml
Enables [modsec](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/modsecurity.html) in detection mode on production so we can be aware of any issues and evaluate if more protection is required.
=> CDPT-1952 Enable modsec detection mode on production

app/controllers/concerns/session_person_creator.rb, app/controllers/tokens_controller.rb, spec/features/person_edit_notifications_spec.rb
When a user inputs their email address for the first time a profile is created and a login URL sent. This URL will take them to their profile page and prompt them to fill in required details such as their team.
If they don't update their profile and generate a login link again at a later date they may end up on the new profile creation page without realising their profile already exists.
Now, if they generate a login link and have not yet updated the mandatory fields, they will be taken to the profile edit page  where they can finish the profile setup.
=> CDPT-2128 Ensure profile completion

app/services/never_logged_in_notifier.rb, spec/services/never_logged_in_notifier_spec.rb
Need to avoid validation when updating the last reminder date for users that are invalid because they have not added a team.
=> Avoid validation when updating user
